// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createActivityLog = `-- name: CreateActivityLog :exec

INSERT INTO activity_logs (user_id, action, entity, entity_id, meta, ip)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateActivityLogParams struct {
	UserID   sql.NullInt64  `json:"user_id"`
	Action   string         `json:"action"`
	Entity   sql.NullString `json:"entity"`
	EntityID sql.NullInt64  `json:"entity_id"`
	Meta     sql.NullString `json:"meta"`
	Ip       sql.NullString `json:"ip"`
}

// activity_logs — audit trail for admin actions and booking state changes.
// meta is a JSON column: pass NULL or valid JSON, never an empty string.
func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, createActivityLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Meta,
		arg.Ip,
	)
	return err
}

const listActivityLogsByUser = `-- name: ListActivityLogsByUser :many
SELECT id, user_id, action, entity, entity_id, meta, ip, created_at FROM activity_logs
WHERE user_id = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListActivityLogsByUserParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Meta,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsForEntity = `-- name: ListActivityLogsForEntity :many
SELECT id, user_id, action, entity, entity_id, meta, ip, created_at FROM activity_logs
WHERE entity = ? AND entity_id = ?
ORDER BY id DESC
LIMIT ?
`

type ListActivityLogsForEntityParams struct {
	Entity   sql.NullString `json:"entity"`
	EntityID sql.NullInt64  `json:"entity_id"`
	Limit    int32          `json:"limit"`
}

// The booking detail timeline in the admin panel.
func (q *Queries) ListActivityLogsForEntity(ctx context.Context, arg ListActivityLogsForEntityParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogsForEntity, arg.Entity, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Meta,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
