// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const bookingCodeTaken = `-- name: BookingCodeTaken :one
SELECT EXISTS(SELECT 1 FROM bookings WHERE booking_code = ?) AS taken
`

func (q *Queries) BookingCodeTaken(ctx context.Context, bookingCode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, bookingCodeTaken, bookingCode)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const cancelBooking = `-- name: CancelBooking :execresult
UPDATE bookings SET status = 'cancelled', cancelled_at = NOW(), cancelled_reason = ?
WHERE id = ? AND status IN ('pending_payment', 'paid', 'confirmed')
`

type CancelBookingParams struct {
	CancelledReason sql.NullString `json:"cancelled_reason"`
	ID              int64          `json:"id"`
}

// Releases the slot: the caller must call ReleaseSlot iff RowsAffected() == 1.
func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, cancelBooking, arg.CancelledReason, arg.ID)
}

const cancelPendingBookingByOwner = `-- name: CancelPendingBookingByOwner :execresult
UPDATE bookings SET status = 'cancelled', cancelled_at = NOW(), cancelled_reason = ?
WHERE id = ? AND user_id = ? AND status = 'pending_payment'
`

type CancelPendingBookingByOwnerParams struct {
	CancelledReason sql.NullString `json:"cancelled_reason"`
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
}

// Phase 9 user-initiated cancellation. Narrower guard than CancelBooking, with
// ownership enforced in the WHERE rather than trusted from the handler.
// Releases the slot: ReleaseSlot iff RowsAffected() == 1.
func (q *Queries) CancelPendingBookingByOwner(ctx context.Context, arg CancelPendingBookingByOwnerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, cancelPendingBookingByOwner, arg.CancelledReason, arg.ID, arg.UserID)
}

const completeBooking = `-- name: CompleteBooking :execresult
UPDATE bookings SET status = 'completed', completed_at = NOW()
WHERE id = ? AND status IN ('paid', 'confirmed')
`

func (q *Queries) CompleteBooking(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeBooking, id)
}

const confirmBooking = `-- name: ConfirmBooking :execresult
UPDATE bookings SET status = 'confirmed', confirmed_at = NOW()
WHERE id = ? AND status = 'paid'
`

func (q *Queries) ConfirmBooking(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, confirmBooking, id)
}

const countBookingsAdmin = `-- name: CountBookingsAdmin :one
SELECT COUNT(*) AS total
FROM bookings b
JOIN schedule_slots sl ON sl.id = b.slot_id
WHERE FIND_IN_SET(CAST(b.status AS CHAR), ?) > 0
  AND (? = 0 OR b.service_id = ?)
  AND sl.slot_date >= ?    AND sl.slot_date <= ?
  AND b.created_at >= ? AND b.created_at <= ?
  AND (b.booking_code   LIKE ?
    OR b.customer_name  LIKE ?
    OR b.customer_phone LIKE ?)
`

type CountBookingsAdminParams struct {
	StatusList  string    `json:"status_list"`
	ServiceID   int64     `json:"service_id"`
	SlotFrom    time.Time `json:"slot_from"`
	SlotTo      time.Time `json:"slot_to"`
	CreatedFrom time.Time `json:"created_from"`
	CreatedTo   time.Time `json:"created_to"`
	Search      string    `json:"search"`
}

func (q *Queries) CountBookingsAdmin(ctx context.Context, arg CountBookingsAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookingsAdmin,
		arg.StatusList,
		arg.ServiceID,
		arg.ServiceID,
		arg.SlotFrom,
		arg.SlotTo,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countBookingsByStatusInRange = `-- name: CountBookingsByStatusInRange :many
SELECT b.status, COUNT(*) AS total
FROM bookings b
JOIN schedule_slots sl ON sl.id = b.slot_id
WHERE sl.slot_date BETWEEN ? AND ?
GROUP BY b.status
`

type CountBookingsByStatusInRangeParams struct {
	FromSlotDate time.Time `json:"from_slot_date"`
	ToSlotDate   time.Time `json:"to_slot_date"`
}

type CountBookingsByStatusInRangeRow struct {
	Status BookingsStatus `json:"status"`
	Total  int64          `json:"total"`
}

// The dashboard's counts by status, over a slot-date range.
func (q *Queries) CountBookingsByStatusInRange(ctx context.Context, arg CountBookingsByStatusInRangeParams) ([]CountBookingsByStatusInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, countBookingsByStatusInRange, arg.FromSlotDate, arg.ToSlotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBookingsByStatusInRangeRow{}
	for rows.Next() {
		var i CountBookingsByStatusInRangeRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBookingsByUser = `-- name: CountBookingsByUser :one
SELECT COUNT(*) AS total FROM bookings
WHERE user_id = ? AND FIND_IN_SET(CAST(status AS CHAR), ?) > 0
`

type CountBookingsByUserParams struct {
	UserID     int64  `json:"user_id"`
	StatusList string `json:"status_list"`
}

func (q *Queries) CountBookingsByUser(ctx context.Context, arg CountBookingsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookingsByUser, arg.UserID, arg.StatusList)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBooking = `-- name: CreateBooking :execresult

INSERT INTO bookings (booking_code, user_id, service_id, slot_id,
                      customer_name, customer_phone, customer_address,
                      latitude, longitude, notes,
                      price_amount, status, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending_payment', ?)
`

type CreateBookingParams struct {
	BookingCode     string         `json:"booking_code"`
	UserID          int64          `json:"user_id"`
	ServiceID       int64          `json:"service_id"`
	SlotID          int64          `json:"slot_id"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
	CustomerAddress sql.NullString `json:"customer_address"`
	Latitude        sql.NullString `json:"latitude"`
	Longitude       sql.NullString `json:"longitude"`
	Notes           sql.NullString `json:"notes"`
	PriceAmount     string         `json:"price_amount"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
}

// bookings — the booking lifecycle.
//
// Slot-holding statuses: pending_payment, paid, confirmed, completed.
// Slot-releasing statuses: cancelled, expired.
//
// EVERY status transition below is :execresult and guarded by the current
// status. RowsAffected() == 1 IS the definition of "a real status transition",
// and is the only thing that authorises a ReleaseSlot call. RowsAffected() == 0
// means the transition was already applied — a Midtrans retry, a double-clicked
// button, the expiry ticker racing the webhook — in which case do nothing else
// and report success.
// active_slot_id is a generated column and must not appear in the column list.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBooking,
		arg.BookingCode,
		arg.UserID,
		arg.ServiceID,
		arg.SlotID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CustomerAddress,
		arg.Latitude,
		arg.Longitude,
		arg.Notes,
		arg.PriceAmount,
		arg.ExpiresAt,
	)
}

const expireBooking = `-- name: ExpireBooking :execresult
UPDATE bookings SET status = 'expired'
WHERE id = ? AND status = 'pending_payment'
`

// Releases the slot: the caller must call ReleaseSlot iff RowsAffected() == 1.
func (q *Queries) ExpireBooking(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, expireBooking, id)
}

const getBooking = `-- name: GetBooking :one
SELECT id, booking_code, user_id, service_id, slot_id, customer_name, customer_phone, customer_address, latitude, longitude, notes, price_amount, status, expires_at, confirmed_at, completed_at, cancelled_at, cancelled_reason, reminder_sent_at, active_slot_id, created_at, updated_at FROM bookings WHERE id = ? LIMIT 1
`

func (q *Queries) GetBooking(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.ServiceID,
		&i.SlotID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.PriceAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledReason,
		&i.ReminderSentAt,
		&i.ActiveSlotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingAdminDetail = `-- name: GetBookingAdminDetail :one
SELECT b.id, b.booking_code, b.user_id, b.service_id, b.slot_id, b.customer_name, b.customer_phone, b.customer_address, b.latitude, b.longitude, b.notes, b.price_amount, b.status, b.expires_at, b.confirmed_at, b.completed_at, b.cancelled_at, b.cancelled_reason, b.reminder_sent_at, b.active_slot_id, b.created_at, b.updated_at,
       sv.name             AS service_name,
       sv.slug             AS service_slug,
       sv.duration_minutes AS service_duration_minutes,
       sl.slot_date        AS slot_date,
       sl.start_time       AS slot_start_time,
       sl.end_time         AS slot_end_time,
       sl.starts_at        AS slot_starts_at,
       sl.capacity         AS slot_capacity,
       sl.booked_count     AS slot_booked_count,
       sl.is_active        AS slot_is_active,
       u.name              AS user_name,
       u.email             AS user_email,
       u.phone             AS user_phone,
       u.appskep_user_id   AS user_appskep_id
FROM bookings b
JOIN services       sv ON sv.id = b.service_id
JOIN schedule_slots sl ON sl.id = b.slot_id
JOIN users          u  ON u.id  = b.user_id
WHERE b.id = ?
LIMIT 1
`

type GetBookingAdminDetailRow struct {
	ID                     int64          `json:"id"`
	BookingCode            string         `json:"booking_code"`
	UserID                 int64          `json:"user_id"`
	ServiceID              int64          `json:"service_id"`
	SlotID                 int64          `json:"slot_id"`
	CustomerName           string         `json:"customer_name"`
	CustomerPhone          string         `json:"customer_phone"`
	CustomerAddress        sql.NullString `json:"customer_address"`
	Latitude               sql.NullString `json:"latitude"`
	Longitude              sql.NullString `json:"longitude"`
	Notes                  sql.NullString `json:"notes"`
	PriceAmount            string         `json:"price_amount"`
	Status                 BookingsStatus `json:"status"`
	ExpiresAt              sql.NullTime   `json:"expires_at"`
	ConfirmedAt            sql.NullTime   `json:"confirmed_at"`
	CompletedAt            sql.NullTime   `json:"completed_at"`
	CancelledAt            sql.NullTime   `json:"cancelled_at"`
	CancelledReason        sql.NullString `json:"cancelled_reason"`
	ReminderSentAt         sql.NullTime   `json:"reminder_sent_at"`
	ActiveSlotID           sql.NullInt64  `json:"active_slot_id"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	ServiceName            string         `json:"service_name"`
	ServiceSlug            string         `json:"service_slug"`
	ServiceDurationMinutes int32          `json:"service_duration_minutes"`
	SlotDate               time.Time      `json:"slot_date"`
	SlotStartTime          string         `json:"slot_start_time"`
	SlotEndTime            string         `json:"slot_end_time"`
	SlotStartsAt           time.Time      `json:"slot_starts_at"`
	SlotCapacity           int32          `json:"slot_capacity"`
	SlotBookedCount        int32          `json:"slot_booked_count"`
	SlotIsActive           bool           `json:"slot_is_active"`
	UserName               string         `json:"user_name"`
	UserEmail              string         `json:"user_email"`
	UserPhone              sql.NullString `json:"user_phone"`
	UserAppskepID          uint64         `json:"user_appskep_id"`
}

// Everything the admin detail page renders, in one round trip. The customer's
// own page uses GetBookingDetailByCode; this one is by id, carries the slot's
// capacity and the local user record, and has no ownership predicate — the route
// is behind RequireAdmin.
func (q *Queries) GetBookingAdminDetail(ctx context.Context, id int64) (GetBookingAdminDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingAdminDetail, id)
	var i GetBookingAdminDetailRow
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.ServiceID,
		&i.SlotID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.PriceAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledReason,
		&i.ReminderSentAt,
		&i.ActiveSlotID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceName,
		&i.ServiceSlug,
		&i.ServiceDurationMinutes,
		&i.SlotDate,
		&i.SlotStartTime,
		&i.SlotEndTime,
		&i.SlotStartsAt,
		&i.SlotCapacity,
		&i.SlotBookedCount,
		&i.SlotIsActive,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserAppskepID,
	)
	return i, err
}

const getBookingByCode = `-- name: GetBookingByCode :one
SELECT id, booking_code, user_id, service_id, slot_id, customer_name, customer_phone, customer_address, latitude, longitude, notes, price_amount, status, expires_at, confirmed_at, completed_at, cancelled_at, cancelled_reason, reminder_sent_at, active_slot_id, created_at, updated_at FROM bookings WHERE booking_code = ? LIMIT 1
`

func (q *Queries) GetBookingByCode(ctx context.Context, bookingCode string) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByCode, bookingCode)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.ServiceID,
		&i.SlotID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.PriceAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledReason,
		&i.ReminderSentAt,
		&i.ActiveSlotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByCodeForUpdate = `-- name: GetBookingByCodeForUpdate :one
SELECT id, booking_code, user_id, service_id, slot_id, customer_name, customer_phone, customer_address, latitude, longitude, notes, price_amount, status, expires_at, confirmed_at, completed_at, cancelled_at, cancelled_reason, reminder_sent_at, active_slot_id, created_at, updated_at FROM bookings WHERE booking_code = ? FOR UPDATE
`

func (q *Queries) GetBookingByCodeForUpdate(ctx context.Context, bookingCode string) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByCodeForUpdate, bookingCode)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.ServiceID,
		&i.SlotID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.PriceAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledReason,
		&i.ReminderSentAt,
		&i.ActiveSlotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingDetailByCode = `-- name: GetBookingDetailByCode :one
SELECT b.id, b.booking_code, b.user_id, b.service_id, b.slot_id,
       b.customer_name, b.customer_phone, b.customer_address,
       b.latitude, b.longitude, b.notes,
       b.price_amount, b.status, b.expires_at, b.cancelled_reason,
       b.created_at, b.updated_at,
       sv.name       AS service_name,
       sv.slug       AS service_slug,
       sv.image_path AS service_image_path,
       sl.slot_date  AS slot_date,
       sl.start_time AS slot_start_time,
       sl.end_time   AS slot_end_time,
       sl.starts_at  AS slot_starts_at
FROM bookings b
JOIN services       sv ON sv.id = b.service_id
JOIN schedule_slots sl ON sl.id = b.slot_id
WHERE b.booking_code = ?
LIMIT 1
`

type GetBookingDetailByCodeRow struct {
	ID               int64          `json:"id"`
	BookingCode      string         `json:"booking_code"`
	UserID           int64          `json:"user_id"`
	ServiceID        int64          `json:"service_id"`
	SlotID           int64          `json:"slot_id"`
	CustomerName     string         `json:"customer_name"`
	CustomerPhone    string         `json:"customer_phone"`
	CustomerAddress  sql.NullString `json:"customer_address"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Notes            sql.NullString `json:"notes"`
	PriceAmount      string         `json:"price_amount"`
	Status           BookingsStatus `json:"status"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	CancelledReason  sql.NullString `json:"cancelled_reason"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ServiceName      string         `json:"service_name"`
	ServiceSlug      string         `json:"service_slug"`
	ServiceImagePath sql.NullString `json:"service_image_path"`
	SlotDate         time.Time      `json:"slot_date"`
	SlotStartTime    string         `json:"slot_start_time"`
	SlotEndTime      string         `json:"slot_end_time"`
	SlotStartsAt     time.Time      `json:"slot_starts_at"`
}

// The konfirmasi / pembayaran pages: everything needed to render in one round
// trip.
func (q *Queries) GetBookingDetailByCode(ctx context.Context, bookingCode string) (GetBookingDetailByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingDetailByCode, bookingCode)
	var i GetBookingDetailByCodeRow
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.ServiceID,
		&i.SlotID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.PriceAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CancelledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceName,
		&i.ServiceSlug,
		&i.ServiceImagePath,
		&i.SlotDate,
		&i.SlotStartTime,
		&i.SlotEndTime,
		&i.SlotStartsAt,
	)
	return i, err
}

const getBookingForUpdate = `-- name: GetBookingForUpdate :one
SELECT id, booking_code, user_id, service_id, slot_id, customer_name, customer_phone, customer_address, latitude, longitude, notes, price_amount, status, expires_at, confirmed_at, completed_at, cancelled_at, cancelled_reason, reminder_sent_at, active_slot_id, created_at, updated_at FROM bookings WHERE id = ? FOR UPDATE
`

// If this transaction will also change booked_count, take GetSlotForUpdate
// first (see the lock order note in schedules.sql).
func (q *Queries) GetBookingForUpdate(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingForUpdate, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.ServiceID,
		&i.SlotID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.PriceAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledReason,
		&i.ReminderSentAt,
		&i.ActiveSlotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestBookingContactByUser = `-- name: GetLatestBookingContactByUser :one
SELECT customer_phone, customer_address, latitude, longitude
FROM bookings
WHERE user_id = ?
ORDER BY id DESC
LIMIT 1
`

type GetLatestBookingContactByUserRow struct {
	CustomerPhone   string         `json:"customer_phone"`
	CustomerAddress sql.NullString `json:"customer_address"`
	Latitude        sql.NullString `json:"latitude"`
	Longitude       sql.NullString `json:"longitude"`
}

// What this customer told us last time, to prefill the next booking form with.
//
// Any status: a cancelled or expired booking still recorded where this person
// lives and how to reach them. ORDER BY id, not created_at — id is the primary
// key and strictly increasing, so two bookings made in the same second cannot
// tie and pick an arbitrary winner.
func (q *Queries) GetLatestBookingContactByUser(ctx context.Context, userID int64) (GetLatestBookingContactByUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestBookingContactByUser, userID)
	var i GetLatestBookingContactByUserRow
	err := row.Scan(
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getSlotHoldingBookingForUser = `-- name: GetSlotHoldingBookingForUser :one
SELECT id, booking_code, user_id, service_id, slot_id, customer_name, customer_phone, customer_address, latitude, longitude, notes, price_amount, status, expires_at, confirmed_at, completed_at, cancelled_at, cancelled_reason, reminder_sent_at, active_slot_id, created_at, updated_at FROM bookings
WHERE slot_id = ? AND user_id = ? AND status NOT IN ('cancelled', 'expired')
LIMIT 1
`

type GetSlotHoldingBookingForUserParams struct {
	SlotID int64 `json:"slot_id"`
	UserID int64 `json:"user_id"`
}

// Pre-flight duplicate check, so the user gets a friendly message instead of a
// constraint error. It is only a nicety: the real guarantee is the unique index
// uq_bookings_active_slot_user, which cannot be bypassed by application code.
func (q *Queries) GetSlotHoldingBookingForUser(ctx context.Context, arg GetSlotHoldingBookingForUserParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getSlotHoldingBookingForUser, arg.SlotID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookingCode,
		&i.UserID,
		&i.ServiceID,
		&i.SlotID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Latitude,
		&i.Longitude,
		&i.Notes,
		&i.PriceAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledReason,
		&i.ReminderSentAt,
		&i.ActiveSlotID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsAdmin = `-- name: ListBookingsAdmin :many

SELECT b.id, b.booking_code, b.user_id, b.service_id, b.slot_id,
       b.customer_name, b.customer_phone, b.notes,
       b.price_amount, b.status, b.expires_at, b.created_at,
       sv.name       AS service_name,
       sv.slug       AS service_slug,
       sl.slot_date  AS slot_date,
       sl.start_time AS slot_start_time,
       sl.end_time   AS slot_end_time,
       sl.starts_at  AS slot_starts_at,
       u.name        AS user_name,
       u.email       AS user_email
FROM bookings b
JOIN services       sv ON sv.id = b.service_id
JOIN schedule_slots sl ON sl.id = b.slot_id
JOIN users          u  ON u.id  = b.user_id
WHERE FIND_IN_SET(CAST(b.status AS CHAR), ?) > 0
  AND (? = 0 OR b.service_id = ?)
  AND sl.slot_date >= ?    AND sl.slot_date <= ?
  AND b.created_at >= ? AND b.created_at <= ?
  AND (b.booking_code   LIKE ?
    OR b.customer_name  LIKE ?
    OR b.customer_phone LIKE ?)
ORDER BY CASE WHEN ? = 1 THEN sl.starts_at END ASC,
         CASE WHEN ? = 0 THEN sl.starts_at END DESC,
         b.id DESC
LIMIT ? OFFSET ?
`

type ListBookingsAdminParams struct {
	StatusList  string      `json:"status_list"`
	ServiceID   int64       `json:"service_id"`
	SlotFrom    time.Time   `json:"slot_from"`
	SlotTo      time.Time   `json:"slot_to"`
	CreatedFrom time.Time   `json:"created_from"`
	CreatedTo   time.Time   `json:"created_to"`
	Search      string      `json:"search"`
	OldestFirst interface{} `json:"oldest_first"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListBookingsAdminRow struct {
	ID            int64          `json:"id"`
	BookingCode   string         `json:"booking_code"`
	UserID        int64          `json:"user_id"`
	ServiceID     int64          `json:"service_id"`
	SlotID        int64          `json:"slot_id"`
	CustomerName  string         `json:"customer_name"`
	CustomerPhone string         `json:"customer_phone"`
	Notes         sql.NullString `json:"notes"`
	PriceAmount   string         `json:"price_amount"`
	Status        BookingsStatus `json:"status"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
	ServiceName   string         `json:"service_name"`
	ServiceSlug   string         `json:"service_slug"`
	SlotDate      time.Time      `json:"slot_date"`
	SlotStartTime string         `json:"slot_start_time"`
	SlotEndTime   string         `json:"slot_end_time"`
	SlotStartsAt  time.Time      `json:"slot_starts_at"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
}

// ---------------------------------------------------------------------------
// Admin panel (Phase 10)
//
// One WHERE clause serves every filter combination, following the same
// techniques as ListBookingsByUser above: a comma-joined status list through
// FIND_IN_SET (sqlc's MySQL engine has no sqlc.slice()), "%" for an empty search
// box, and a 0 sentinel for "any layanan".
//
// BOTH date ranges are always applied, and the caller widens the one the
// operator did not choose (?tanggal=jadwal|dibuat). That is not a style
// preference. sqlc's MySQL engine mis-binds BETWEEN here in two different ways,
// and each produces SQL whose placeholder count does not match the generated
// call — a runtime failure on the first request, invisible at generate time:
//
//   - `(CASE ... END) BETWEEN ? AND ?` and `DATE(created_at) BETWEEN ? AND ?`
//     emit the placeholders but DROP both parameters. An expression on the left
//     of BETWEEN is not bound at all.
//   - `b.created_at BETWEEN ? AND ?` DUPLICATES each parameter once per joined
//     table that also has a created_at column — four copies here, table
//     qualifier ignored.
//
// `col >= ? AND col <= ?` binds correctly in every case, and is what all three
// admin queries below use. Two plain columns are also index-friendly, which the
// CASE form was not.
//
// created_at is a DATETIME, so the caller passes an end-of-day instant for the
// upper bound; a bare date there would cut at midnight and hide the last day.
// ---------------------------------------------------------------------------
// Schedule order, direction chosen by a parameter rather than by a second
// near-identical query. The unused branch evaluates to a constant NULL, which
// orders nothing. Ordering is always by the slot's instant, whichever date the
// operator filtered on: this list is a day sheet, and reading it in schedule
// order is what an operator is doing with it.
//
// oldest_first types as interface{} — sqlc's MySQL engine cannot infer a Go type
// for a parameter compared against a literal. Wrapping it in CAST(... AS
// UNSIGNED) does type it, but as TWO separate int64 fields that a caller could
// set to disagreeing values and silently get a wrong order; one untyped field
// bound twice cannot disagree with itself. The single caller passes 0 or 1.
func (q *Queries) ListBookingsAdmin(ctx context.Context, arg ListBookingsAdminParams) ([]ListBookingsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsAdmin,
		arg.StatusList,
		arg.ServiceID,
		arg.ServiceID,
		arg.SlotFrom,
		arg.SlotTo,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.OldestFirst,
		arg.OldestFirst,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsAdminRow{}
	for rows.Next() {
		var i ListBookingsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingCode,
			&i.UserID,
			&i.ServiceID,
			&i.SlotID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Notes,
			&i.PriceAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ServiceName,
			&i.ServiceSlug,
			&i.SlotDate,
			&i.SlotStartTime,
			&i.SlotEndTime,
			&i.SlotStartsAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsBySlotDate = `-- name: ListBookingsBySlotDate :many
SELECT b.id, b.booking_code, b.status, b.customer_name, b.customer_phone,
       b.price_amount,
       sv.name       AS service_name,
       sl.start_time AS slot_start_time,
       sl.end_time   AS slot_end_time
FROM bookings b
JOIN services       sv ON sv.id = b.service_id
JOIN schedule_slots sl ON sl.id = b.slot_id
WHERE sl.slot_date = ? AND b.status NOT IN ('cancelled', 'expired')
ORDER BY sl.start_time ASC, b.id ASC
`

type ListBookingsBySlotDateRow struct {
	ID            int64          `json:"id"`
	BookingCode   string         `json:"booking_code"`
	Status        BookingsStatus `json:"status"`
	CustomerName  string         `json:"customer_name"`
	CustomerPhone string         `json:"customer_phone"`
	PriceAmount   string         `json:"price_amount"`
	ServiceName   string         `json:"service_name"`
	SlotStartTime string         `json:"slot_start_time"`
	SlotEndTime   string         `json:"slot_end_time"`
}

// The dashboard day sheet: who is coming on one date, in time order. Released
// bookings are excluded — a cancelled booking is not on today's list.
func (q *Queries) ListBookingsBySlotDate(ctx context.Context, slotDate time.Time) ([]ListBookingsBySlotDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsBySlotDate, slotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsBySlotDateRow{}
	for rows.Next() {
		var i ListBookingsBySlotDateRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingCode,
			&i.Status,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.PriceAmount,
			&i.ServiceName,
			&i.SlotStartTime,
			&i.SlotEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT b.id, b.booking_code, b.status, b.price_amount, b.expires_at, b.created_at,
       sv.name       AS service_name,
       sv.slug       AS service_slug,
       sl.slot_date  AS slot_date,
       sl.start_time AS slot_start_time,
       sl.end_time   AS slot_end_time
FROM bookings b
JOIN services       sv ON sv.id = b.service_id
JOIN schedule_slots sl ON sl.id = b.slot_id
WHERE b.user_id = ? AND FIND_IN_SET(CAST(b.status AS CHAR), ?) > 0
ORDER BY b.created_at DESC
LIMIT ? OFFSET ?
`

type ListBookingsByUserParams struct {
	UserID     int64  `json:"user_id"`
	StatusList string `json:"status_list"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListBookingsByUserRow struct {
	ID            int64          `json:"id"`
	BookingCode   string         `json:"booking_code"`
	Status        BookingsStatus `json:"status"`
	PriceAmount   string         `json:"price_amount"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
	ServiceName   string         `json:"service_name"`
	ServiceSlug   string         `json:"service_slug"`
	SlotDate      time.Time      `json:"slot_date"`
	SlotStartTime string         `json:"slot_start_time"`
	SlotEndTime   string         `json:"slot_end_time"`
}

// Halaman riwayat. Pass a comma-joined status list; for "all", pass
// "pending_payment,paid,confirmed,completed,cancelled,expired".
//
// FIND_IN_SET avoids sqlc.slice(), which the MySQL engine does not support. The
// CAST is required: an ENUM in a numeric context yields its ordinal, not its
// label, so FIND_IN_SET would silently match the wrong rows without it.
func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByUser,
		arg.UserID,
		arg.StatusList,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByUserRow{}
	for rows.Next() {
		var i ListBookingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingCode,
			&i.Status,
			&i.PriceAmount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ServiceName,
			&i.ServiceSlug,
			&i.SlotDate,
			&i.SlotStartTime,
			&i.SlotEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForExport = `-- name: ListBookingsForExport :many
SELECT b.id, b.booking_code, b.status, b.customer_name, b.customer_phone,
       b.customer_address, b.latitude, b.longitude,
       b.notes, b.price_amount, b.created_at,
       b.confirmed_at, b.completed_at, b.cancelled_at, b.cancelled_reason,
       sv.name       AS service_name,
       sl.slot_date  AS slot_date,
       sl.start_time AS slot_start_time,
       sl.end_time   AS slot_end_time,
       u.name        AS user_name,
       u.email       AS user_email
FROM bookings b
JOIN services       sv ON sv.id = b.service_id
JOIN schedule_slots sl ON sl.id = b.slot_id
JOIN users          u  ON u.id  = b.user_id
WHERE FIND_IN_SET(CAST(b.status AS CHAR), ?) > 0
  AND (? = 0 OR b.service_id = ?)
  AND sl.slot_date >= ?    AND sl.slot_date <= ?
  AND b.created_at >= ? AND b.created_at <= ?
  AND (b.booking_code   LIKE ?
    OR b.customer_name  LIKE ?
    OR b.customer_phone LIKE ?)
ORDER BY sl.slot_date ASC, sl.start_time ASC, b.id ASC
LIMIT ?
`

type ListBookingsForExportParams struct {
	StatusList  string    `json:"status_list"`
	ServiceID   int64     `json:"service_id"`
	SlotFrom    time.Time `json:"slot_from"`
	SlotTo      time.Time `json:"slot_to"`
	CreatedFrom time.Time `json:"created_from"`
	CreatedTo   time.Time `json:"created_to"`
	Search      string    `json:"search"`
	Limit       int32     `json:"limit"`
}

type ListBookingsForExportRow struct {
	ID              int64          `json:"id"`
	BookingCode     string         `json:"booking_code"`
	Status          BookingsStatus `json:"status"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
	CustomerAddress sql.NullString `json:"customer_address"`
	Latitude        sql.NullString `json:"latitude"`
	Longitude       sql.NullString `json:"longitude"`
	Notes           sql.NullString `json:"notes"`
	PriceAmount     string         `json:"price_amount"`
	CreatedAt       time.Time      `json:"created_at"`
	ConfirmedAt     sql.NullTime   `json:"confirmed_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CancelledAt     sql.NullTime   `json:"cancelled_at"`
	CancelledReason sql.NullString `json:"cancelled_reason"`
	ServiceName     string         `json:"service_name"`
	SlotDate        time.Time      `json:"slot_date"`
	SlotStartTime   string         `json:"slot_start_time"`
	SlotEndTime     string         `json:"slot_end_time"`
	UserName        string         `json:"user_name"`
	UserEmail       string         `json:"user_email"`
}

// The CSV export. Same predicate as the list, no OFFSET, and a LIMIT the service
// sets so an export cannot pull an unbounded result set into memory.
func (q *Queries) ListBookingsForExport(ctx context.Context, arg ListBookingsForExportParams) ([]ListBookingsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsForExport,
		arg.StatusList,
		arg.ServiceID,
		arg.ServiceID,
		arg.SlotFrom,
		arg.SlotTo,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsForExportRow{}
	for rows.Next() {
		var i ListBookingsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingCode,
			&i.Status,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerAddress,
			&i.Latitude,
			&i.Longitude,
			&i.Notes,
			&i.PriceAmount,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CancelledReason,
			&i.ServiceName,
			&i.SlotDate,
			&i.SlotStartTime,
			&i.SlotEndTime,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForReminder = `-- name: ListBookingsForReminder :many
SELECT b.id
FROM bookings b
JOIN schedule_slots sl ON sl.id = b.slot_id
WHERE sl.slot_date = ?
  AND b.status IN ('paid', 'confirmed')
  AND b.reminder_sent_at IS NULL
ORDER BY b.id ASC
LIMIT ?
`

type ListBookingsForReminderParams struct {
	SlotDate time.Time `json:"slot_date"`
	Limit    int32     `json:"limit"`
}

// The Phase 11 H-1 reminder sweep's work queue: bookings on one slot date that
// are still coming and have not been reminded yet.
//
// 'paid' as well as 'confirmed': confirming is an operator action that may never
// happen, and a customer who has paid is coming regardless. 'completed' is
// excluded because a completed booking is in the past by definition.
//
// Only the id is needed — the worker re-reads the whole booking through
// GetBookingAdminDetail at send time, so a reminder describes the booking as it
// is when it goes out rather than as it was when it was queued.
func (q *Queries) ListBookingsForReminder(ctx context.Context, arg ListBookingsForReminderParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsForReminder, arg.SlotDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingBookings = `-- name: ListExpiredPendingBookings :many

SELECT id, slot_id FROM bookings
WHERE status = 'pending_payment'
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
ORDER BY id ASC
LIMIT ?
`

type ListExpiredPendingBookingsRow struct {
	ID     int64 `json:"id"`
	SlotID int64 `json:"slot_id"`
}

// ---------------------------------------------------------------------------
// Lists
// ---------------------------------------------------------------------------
// The Phase 7 expiry ticker's work queue. slot_id is selected so the worker can
// take the SLOT lock first, preserving the canonical lock order.
//
// NOW() rather than a timestamp passed from Go: one clock decides expiry, so
// app-server clock skew cannot expire bookings early or leak slots.
func (q *Queries) ListExpiredPendingBookings(ctx context.Context, limit int32) ([]ListExpiredPendingBookingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPendingBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredPendingBookingsRow{}
	for rows.Next() {
		var i ListExpiredPendingBookingsRow
		if err := rows.Scan(&i.ID, &i.SlotID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBookingPaid = `-- name: MarkBookingPaid :execresult

UPDATE bookings SET status = 'paid'
WHERE id = ? AND status = 'pending_payment'
`

// ---------------------------------------------------------------------------
// Status transitions
// ---------------------------------------------------------------------------
// Applied only by the Midtrans webhook (settlement, or capture + credit_card +
// fraud_status=accept). Never from a Snap token response or a client callback.
func (q *Queries) MarkBookingPaid(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, markBookingPaid, id)
}

const markBookingReminderSent = `-- name: MarkBookingReminderSent :execresult
UPDATE bookings SET reminder_sent_at = NOW()
WHERE id = ? AND reminder_sent_at IS NULL
`

// Claims one booking for the reminder sweep. RowsAffected() == 1 is the only
// thing that authorises sending the email — the same rule that guards every
// status transition above. Claim-then-send is deliberate: a duplicate reminder
// is worse than a missing one, so a send that fails afterwards is not retried.
func (q *Queries) MarkBookingReminderSent(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, markBookingReminderSent, id)
}

const rescheduleBooking = `-- name: RescheduleBooking :execresult
UPDATE bookings SET slot_id = ?
WHERE id = ? AND status IN ('pending_payment', 'paid', 'confirmed')
`

type RescheduleBookingParams struct {
	SlotID int64 `json:"slot_id"`
	ID     int64 `json:"id"`
}

// Phase 10. The caller must decrement the old slot and increment the new one in
// the same transaction, taking both slot locks in ascending id order.
func (q *Queries) RescheduleBooking(ctx context.Context, arg RescheduleBookingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rescheduleBooking, arg.SlotID, arg.ID)
}

const updateBookingNotes = `-- name: UpdateBookingNotes :exec
UPDATE bookings SET notes = ? WHERE id = ?
`

type UpdateBookingNotesParams struct {
	Notes sql.NullString `json:"notes"`
	ID    int64          `json:"id"`
}

// The only booking field an admin may edit freely. Everything else is either a
// status transition or a reschedule, both of which move a slot.
func (q *Queries) UpdateBookingNotes(ctx context.Context, arg UpdateBookingNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingNotes, arg.Notes, arg.ID)
	return err
}
