// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type BookingsStatus string

const (
	BookingsStatusPendingPayment BookingsStatus = "pending_payment"
	BookingsStatusPaid           BookingsStatus = "paid"
	BookingsStatusConfirmed      BookingsStatus = "confirmed"
	BookingsStatusCompleted      BookingsStatus = "completed"
	BookingsStatusCancelled      BookingsStatus = "cancelled"
	BookingsStatusExpired        BookingsStatus = "expired"
)

func (e *BookingsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingsStatus(s)
	case string:
		*e = BookingsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingsStatus: %T", src)
	}
	return nil
}

type NullBookingsStatus struct {
	BookingsStatus BookingsStatus `json:"bookings_status"`
	Valid          bool           `json:"valid"` // Valid is true if BookingsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingsStatus), nil
}

type UsersRole string

const (
	UsersRoleUser  UsersRole = "user"
	UsersRoleAdmin UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type ActivityLog struct {
	ID        int64          `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	Action    string         `json:"action"`
	Entity    sql.NullString `json:"entity"`
	EntityID  sql.NullInt64  `json:"entity_id"`
	Meta      sql.NullString `json:"meta"`
	Ip        sql.NullString `json:"ip"`
	CreatedAt time.Time      `json:"created_at"`
}

type Booking struct {
	ID              int64          `json:"id"`
	BookingCode     string         `json:"booking_code"`
	UserID          int64          `json:"user_id"`
	ServiceID       int64          `json:"service_id"`
	SlotID          int64          `json:"slot_id"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
	CustomerAddress sql.NullString `json:"customer_address"`
	Notes           sql.NullString `json:"notes"`
	PriceAmount     string         `json:"price_amount"`
	Status          BookingsStatus `json:"status"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	ConfirmedAt     sql.NullTime   `json:"confirmed_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CancelledAt     sql.NullTime   `json:"cancelled_at"`
	CancelledReason sql.NullString `json:"cancelled_reason"`
	ReminderSentAt  sql.NullTime   `json:"reminder_sent_at"`
	ActiveSlotID    sql.NullInt64  `json:"active_slot_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Payment struct {
	ID                int64          `json:"id"`
	BookingID         int64          `json:"booking_id"`
	OrderID           string         `json:"order_id"`
	GrossAmount       string         `json:"gross_amount"`
	PaymentType       sql.NullString `json:"payment_type"`
	TransactionID     sql.NullString `json:"transaction_id"`
	TransactionStatus sql.NullString `json:"transaction_status"`
	TransactionTime   sql.NullTime   `json:"transaction_time"`
	FraudStatus       sql.NullString `json:"fraud_status"`
	StatusCode        sql.NullString `json:"status_code"`
	Bank              sql.NullString `json:"bank"`
	VaNumber          sql.NullString `json:"va_number"`
	SnapToken         sql.NullString `json:"snap_token"`
	SnapRedirectUrl   sql.NullString `json:"snap_redirect_url"`
	PaidAt            sql.NullTime   `json:"paid_at"`
	ExpiredAt         sql.NullTime   `json:"expired_at"`
	CancelledAt       sql.NullTime   `json:"cancelled_at"`
	RawResponse       sql.NullString `json:"raw_response"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type PaymentNotification struct {
	ID                int64           `json:"id"`
	OrderID           string          `json:"order_id"`
	TransactionStatus sql.NullString  `json:"transaction_status"`
	FraudStatus       sql.NullString  `json:"fraud_status"`
	StatusCode        sql.NullString  `json:"status_code"`
	GrossAmount       sql.NullString  `json:"gross_amount"`
	SignatureValid    bool            `json:"signature_valid"`
	Processed         bool            `json:"processed"`
	ProcessNote       sql.NullString  `json:"process_note"`
	Payload           json.RawMessage `json:"payload"`
	RemoteIp          sql.NullString  `json:"remote_ip"`
	ReceivedAt        time.Time       `json:"received_at"`
}

type ScheduleSlot struct {
	ID          int64          `json:"id"`
	ServiceID   sql.NullInt64  `json:"service_id"`
	SlotDate    time.Time      `json:"slot_date"`
	StartTime   string         `json:"start_time"`
	EndTime     string         `json:"end_time"`
	StartsAt    time.Time      `json:"starts_at"`
	EndsAt      time.Time      `json:"ends_at"`
	Capacity    int32          `json:"capacity"`
	BookedCount int32          `json:"booked_count"`
	IsActive    bool           `json:"is_active"`
	Note        sql.NullString `json:"note"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Service struct {
	ID              int64          `json:"id"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Price           string         `json:"price"`
	DurationMinutes int32          `json:"duration_minutes"`
	ImagePath       sql.NullString `json:"image_path"`
	IsActive        bool           `json:"is_active"`
	IsComingSoon    bool           `json:"is_coming_soon"`
	SortOrder       int32          `json:"sort_order"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Setting struct {
	SettingKey   string         `json:"setting_key"`
	SettingValue sql.NullString `json:"setting_value"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type User struct {
	ID            int64          `json:"id"`
	AppskepUserID uint64         `json:"appskep_user_id"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	Phone         sql.NullString `json:"phone"`
	Address       sql.NullString `json:"address"`
	AvatarPath    sql.NullString `json:"avatar_path"`
	Role          UsersRole      `json:"role"`
	IsActive      bool           `json:"is_active"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
