// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countPaymentsAdmin = `-- name: CountPaymentsAdmin :one
SELECT COUNT(*) AS total
FROM payments p
JOIN bookings b ON b.id = p.booking_id
WHERE FIND_IN_SET(
        CASE WHEN p.paid_at      IS NOT NULL THEN 'paid'
             WHEN p.cancelled_at IS NOT NULL THEN 'cancelled'
             WHEN p.expired_at   IS NOT NULL THEN 'expired'
             ELSE 'pending' END,
        ?) > 0
  AND p.created_at >= ? AND p.created_at <= ?
  AND (p.order_id     LIKE ?
    OR b.booking_code LIKE ?)
`

type CountPaymentsAdminParams struct {
	StateList   string    `json:"state_list"`
	CreatedFrom time.Time `json:"created_from"`
	CreatedTo   time.Time `json:"created_to"`
	Search      string    `json:"search"`
}

func (q *Queries) CountPaymentsAdmin(ctx context.Context, arg CountPaymentsAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPaymentsAdmin,
		arg.StateList,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.Search,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPayment = `-- name: CreatePayment :execresult

INSERT INTO payments (booking_id, order_id, gross_amount, snap_token, snap_redirect_url)
VALUES (?, ?, ?, ?, ?)
`

type CreatePaymentParams struct {
	BookingID       int64          `json:"booking_id"`
	OrderID         string         `json:"order_id"`
	GrossAmount     string         `json:"gross_amount"`
	SnapToken       sql.NullString `json:"snap_token"`
	SnapRedirectUrl sql.NullString `json:"snap_redirect_url"`
}

// payments and payment_notifications — the Midtrans side.
//
// Payment is confirmed ONLY by the webhook (PLAN.md R7). A successful Snap token
// response is not a purchase.
//
// Midtrans retries notifications, and a retry can arrive while the first is
// still in flight. Every transition below is guarded so that re-applying a
// notification affects 0 rows: RowsAffected() == 0 means "already applied",
// which must return 200 and change nothing else.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayment,
		arg.BookingID,
		arg.OrderID,
		arg.GrossAmount,
		arg.SnapToken,
		arg.SnapRedirectUrl,
	)
}

const createPaymentNotification = `-- name: CreatePaymentNotification :execresult

INSERT INTO payment_notifications
  (order_id, transaction_status, fraud_status, status_code, gross_amount,
   signature_valid, payload, remote_ip)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePaymentNotificationParams struct {
	OrderID           string          `json:"order_id"`
	TransactionStatus sql.NullString  `json:"transaction_status"`
	FraudStatus       sql.NullString  `json:"fraud_status"`
	StatusCode        sql.NullString  `json:"status_code"`
	GrossAmount       sql.NullString  `json:"gross_amount"`
	SignatureValid    bool            `json:"signature_valid"`
	Payload           json.RawMessage `json:"payload"`
	RemoteIp          sql.NullString  `json:"remote_ip"`
}

// ---------------------------------------------------------------------------
// Webhook audit log
// ---------------------------------------------------------------------------
// Written BEFORE any validation or processing, for every inbound payload —
// including invalid signatures and order IDs belonging to other Appskep systems
// on the shared merchant account. gross_amount is stored as the exact string
// received because it is an input to the SHA512 signature.
func (q *Queries) CreatePaymentNotification(ctx context.Context, arg CreatePaymentNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPaymentNotification,
		arg.OrderID,
		arg.TransactionStatus,
		arg.FraudStatus,
		arg.StatusCode,
		arg.GrossAmount,
		arg.SignatureValid,
		arg.Payload,
		arg.RemoteIp,
	)
}

const getLatestPaymentForBooking = `-- name: GetLatestPaymentForBooking :one
SELECT id, booking_id, order_id, gross_amount, payment_type, transaction_id, transaction_status, transaction_time, fraud_status, status_code, bank, va_number, snap_token, snap_redirect_url, paid_at, expired_at, cancelled_at, raw_response, created_at, updated_at FROM payments WHERE booking_id = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestPaymentForBooking(ctx context.Context, bookingID int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getLatestPaymentForBooking, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.GrossAmount,
		&i.PaymentType,
		&i.TransactionID,
		&i.TransactionStatus,
		&i.TransactionTime,
		&i.FraudStatus,
		&i.StatusCode,
		&i.Bank,
		&i.VaNumber,
		&i.SnapToken,
		&i.SnapRedirectUrl,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, booking_id, order_id, gross_amount, payment_type, transaction_id, transaction_status, transaction_time, fraud_status, status_code, bank, va_number, snap_token, snap_redirect_url, paid_at, expired_at, cancelled_at, raw_response, created_at, updated_at FROM payments WHERE id = ? LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.GrossAmount,
		&i.PaymentType,
		&i.TransactionID,
		&i.TransactionStatus,
		&i.TransactionTime,
		&i.FraudStatus,
		&i.StatusCode,
		&i.Bank,
		&i.VaNumber,
		&i.SnapToken,
		&i.SnapRedirectUrl,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAdminDetail = `-- name: GetPaymentAdminDetail :one
SELECT p.id, p.booking_id, p.order_id, p.gross_amount, p.payment_type, p.transaction_id, p.transaction_status, p.transaction_time, p.fraud_status, p.status_code, p.bank, p.va_number, p.snap_token, p.snap_redirect_url, p.paid_at, p.expired_at, p.cancelled_at, p.raw_response, p.created_at, p.updated_at,
       b.booking_code   AS booking_code,
       b.status         AS booking_status,
       b.price_amount   AS booking_price_amount,
       b.customer_name  AS customer_name,
       b.customer_phone AS customer_phone,
       sv.name          AS service_name,
       sl.slot_date     AS slot_date,
       sl.start_time    AS slot_start_time,
       sl.end_time      AS slot_end_time,
       u.name           AS user_name,
       u.email          AS user_email
FROM payments p
JOIN bookings       b  ON b.id  = p.booking_id
JOIN services       sv ON sv.id = b.service_id
JOIN schedule_slots sl ON sl.id = b.slot_id
JOIN users          u  ON u.id  = b.user_id
WHERE p.id = ?
LIMIT 1
`

type GetPaymentAdminDetailRow struct {
	ID                 int64          `json:"id"`
	BookingID          int64          `json:"booking_id"`
	OrderID            string         `json:"order_id"`
	GrossAmount        string         `json:"gross_amount"`
	PaymentType        sql.NullString `json:"payment_type"`
	TransactionID      sql.NullString `json:"transaction_id"`
	TransactionStatus  sql.NullString `json:"transaction_status"`
	TransactionTime    sql.NullTime   `json:"transaction_time"`
	FraudStatus        sql.NullString `json:"fraud_status"`
	StatusCode         sql.NullString `json:"status_code"`
	Bank               sql.NullString `json:"bank"`
	VaNumber           sql.NullString `json:"va_number"`
	SnapToken          sql.NullString `json:"snap_token"`
	SnapRedirectUrl    sql.NullString `json:"snap_redirect_url"`
	PaidAt             sql.NullTime   `json:"paid_at"`
	ExpiredAt          sql.NullTime   `json:"expired_at"`
	CancelledAt        sql.NullTime   `json:"cancelled_at"`
	RawResponse        sql.NullString `json:"raw_response"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	BookingCode        string         `json:"booking_code"`
	BookingStatus      BookingsStatus `json:"booking_status"`
	BookingPriceAmount string         `json:"booking_price_amount"`
	CustomerName       string         `json:"customer_name"`
	CustomerPhone      string         `json:"customer_phone"`
	ServiceName        string         `json:"service_name"`
	SlotDate           time.Time      `json:"slot_date"`
	SlotStartTime      string         `json:"slot_start_time"`
	SlotEndTime        string         `json:"slot_end_time"`
	UserName           string         `json:"user_name"`
	UserEmail          string         `json:"user_email"`
}

func (q *Queries) GetPaymentAdminDetail(ctx context.Context, id int64) (GetPaymentAdminDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentAdminDetail, id)
	var i GetPaymentAdminDetailRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.GrossAmount,
		&i.PaymentType,
		&i.TransactionID,
		&i.TransactionStatus,
		&i.TransactionTime,
		&i.FraudStatus,
		&i.StatusCode,
		&i.Bank,
		&i.VaNumber,
		&i.SnapToken,
		&i.SnapRedirectUrl,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookingCode,
		&i.BookingStatus,
		&i.BookingPriceAmount,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ServiceName,
		&i.SlotDate,
		&i.SlotStartTime,
		&i.SlotEndTime,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, booking_id, order_id, gross_amount, payment_type, transaction_id, transaction_status, transaction_time, fraud_status, status_code, bank, va_number, snap_token, snap_redirect_url, paid_at, expired_at, cancelled_at, raw_response, created_at, updated_at FROM payments WHERE order_id = ? LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.GrossAmount,
		&i.PaymentType,
		&i.TransactionID,
		&i.TransactionStatus,
		&i.TransactionTime,
		&i.FraudStatus,
		&i.StatusCode,
		&i.Bank,
		&i.VaNumber,
		&i.SnapToken,
		&i.SnapRedirectUrl,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderIDForUpdate = `-- name: GetPaymentByOrderIDForUpdate :one
SELECT id, booking_id, order_id, gross_amount, payment_type, transaction_id, transaction_status, transaction_time, fraud_status, status_code, bank, va_number, snap_token, snap_redirect_url, paid_at, expired_at, cancelled_at, raw_response, created_at, updated_at FROM payments WHERE order_id = ? FOR UPDATE
`

// The webhook entry point. This lock, plus the guarded UPDATEs below, is what
// makes the notification state machine idempotent under concurrent retries.
func (q *Queries) GetPaymentByOrderIDForUpdate(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderIDForUpdate, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.GrossAmount,
		&i.PaymentType,
		&i.TransactionID,
		&i.TransactionStatus,
		&i.TransactionTime,
		&i.FraudStatus,
		&i.StatusCode,
		&i.Bank,
		&i.VaNumber,
		&i.SnapToken,
		&i.SnapRedirectUrl,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReusablePaymentForBooking = `-- name: GetReusablePaymentForBooking :one
SELECT id, booking_id, order_id, gross_amount, payment_type, transaction_id, transaction_status, transaction_time, fraud_status, status_code, bank, va_number, snap_token, snap_redirect_url, paid_at, expired_at, cancelled_at, raw_response, created_at, updated_at FROM payments
WHERE booking_id         = ?
  AND paid_at           IS NULL
  AND expired_at        IS NULL
  AND cancelled_at      IS NULL
  AND snap_redirect_url IS NOT NULL
  AND gross_amount       = ?
ORDER BY id DESC
LIMIT 1
`

type GetReusablePaymentForBookingParams struct {
	BookingID   int64  `json:"booking_id"`
	GrossAmount string `json:"gross_amount"`
}

// create-order.md:93 — repeated taps of "Bayar sekarang" must return the SAME
// Snap URL rather than minting a new order_id on the shared merchant account.
//
// The "still within the booking's expires_at" leg of the rule is applied in Go
// against the already-loaded booking row, which keeps every parameter here
// directly comparable to a bare column.
func (q *Queries) GetReusablePaymentForBooking(ctx context.Context, arg GetReusablePaymentForBookingParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getReusablePaymentForBooking, arg.BookingID, arg.GrossAmount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.GrossAmount,
		&i.PaymentType,
		&i.TransactionID,
		&i.TransactionStatus,
		&i.TransactionTime,
		&i.FraudStatus,
		&i.StatusCode,
		&i.Bank,
		&i.VaNumber,
		&i.SnapToken,
		&i.SnapRedirectUrl,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentNotificationsByOrderID = `-- name: ListPaymentNotificationsByOrderID :many
SELECT id, order_id, transaction_status, fraud_status, status_code, gross_amount, signature_valid, processed, process_note, payload, remote_ip, received_at FROM payment_notifications WHERE order_id = ? ORDER BY id DESC
`

func (q *Queries) ListPaymentNotificationsByOrderID(ctx context.Context, orderID string) ([]PaymentNotification, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentNotificationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentNotification{}
	for rows.Next() {
		var i PaymentNotification
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TransactionStatus,
			&i.FraudStatus,
			&i.StatusCode,
			&i.GrossAmount,
			&i.SignatureValid,
			&i.Processed,
			&i.ProcessNote,
			&i.Payload,
			&i.RemoteIp,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsAdmin = `-- name: ListPaymentsAdmin :many

SELECT p.id, p.booking_id, p.order_id, p.gross_amount, p.payment_type,
       p.transaction_status, p.fraud_status, p.paid_at, p.expired_at,
       p.cancelled_at, p.created_at,
       CASE WHEN p.paid_at      IS NOT NULL THEN 'paid'
            WHEN p.cancelled_at IS NOT NULL THEN 'cancelled'
            WHEN p.expired_at   IS NOT NULL THEN 'expired'
            ELSE 'pending' END AS state,
       b.booking_code AS booking_code,
       b.status       AS booking_status,
       sv.name        AS service_name,
       u.name         AS user_name,
       u.email        AS user_email
FROM payments p
JOIN bookings b  ON b.id  = p.booking_id
JOIN services sv ON sv.id = b.service_id
JOIN users    u  ON u.id  = b.user_id
WHERE FIND_IN_SET(
        CASE WHEN p.paid_at      IS NOT NULL THEN 'paid'
             WHEN p.cancelled_at IS NOT NULL THEN 'cancelled'
             WHEN p.expired_at   IS NOT NULL THEN 'expired'
             ELSE 'pending' END,
        ?) > 0
  AND p.created_at >= ? AND p.created_at <= ?
  AND (p.order_id     LIKE ?
    OR b.booking_code LIKE ?)
ORDER BY p.id DESC
LIMIT ? OFFSET ?
`

type ListPaymentsAdminParams struct {
	StateList   string    `json:"state_list"`
	CreatedFrom time.Time `json:"created_from"`
	CreatedTo   time.Time `json:"created_to"`
	Search      string    `json:"search"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListPaymentsAdminRow struct {
	ID                int64          `json:"id"`
	BookingID         int64          `json:"booking_id"`
	OrderID           string         `json:"order_id"`
	GrossAmount       string         `json:"gross_amount"`
	PaymentType       sql.NullString `json:"payment_type"`
	TransactionStatus sql.NullString `json:"transaction_status"`
	FraudStatus       sql.NullString `json:"fraud_status"`
	PaidAt            sql.NullTime   `json:"paid_at"`
	ExpiredAt         sql.NullTime   `json:"expired_at"`
	CancelledAt       sql.NullTime   `json:"cancelled_at"`
	CreatedAt         time.Time      `json:"created_at"`
	State             string         `json:"state"`
	BookingCode       string         `json:"booking_code"`
	BookingStatus     BookingsStatus `json:"booking_status"`
	ServiceName       string         `json:"service_name"`
	UserName          string         `json:"user_name"`
	UserEmail         string         `json:"user_email"`
}

// ---------------------------------------------------------------------------
// Admin panel (Phase 10)
//
// A payment has no status column on purpose (see the schema comment): its
// lifecycle is paid_at / expired_at / cancelled_at. The list filter therefore
// runs against a derived state, and the same CASE is selected so the page can
// label a row without re-deriving the rule in Go.
//
// The date range is `>= ? AND <= ?` on a bare column, never
// `DATE(p.created_at) BETWEEN ? AND ?`. See the note in bookings.sql: sqlc's
// MySQL engine mis-binds BETWEEN in both directions here, and only the
// comparison form generates a call whose argument count matches its SQL. The
// caller passes an end-of-day instant for the upper bound, since created_at is a
// DATETIME.
// ---------------------------------------------------------------------------
func (q *Queries) ListPaymentsAdmin(ctx context.Context, arg ListPaymentsAdminParams) ([]ListPaymentsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsAdmin,
		arg.StateList,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsAdminRow{}
	for rows.Next() {
		var i ListPaymentsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.OrderID,
			&i.GrossAmount,
			&i.PaymentType,
			&i.TransactionStatus,
			&i.FraudStatus,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.State,
			&i.BookingCode,
			&i.BookingStatus,
			&i.ServiceName,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForBooking = `-- name: ListPaymentsForBooking :many
SELECT id, booking_id, order_id, gross_amount, payment_type, transaction_id, transaction_status, transaction_time, fraud_status, status_code, bank, va_number, snap_token, snap_redirect_url, paid_at, expired_at, cancelled_at, raw_response, created_at, updated_at FROM payments WHERE booking_id = ? ORDER BY id DESC
`

func (q *Queries) ListPaymentsForBooking(ctx context.Context, bookingID int64) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsForBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.OrderID,
			&i.GrossAmount,
			&i.PaymentType,
			&i.TransactionID,
			&i.TransactionStatus,
			&i.TransactionTime,
			&i.FraudStatus,
			&i.StatusCode,
			&i.Bank,
			&i.VaNumber,
			&i.SnapToken,
			&i.SnapRedirectUrl,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CancelledAt,
			&i.RawResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForExport = `-- name: ListPaymentsForExport :many
SELECT p.id, p.order_id, p.gross_amount, p.payment_type, p.transaction_id,
       p.transaction_status, p.fraud_status, p.bank, p.va_number,
       p.paid_at, p.expired_at, p.cancelled_at, p.created_at,
       CASE WHEN p.paid_at      IS NOT NULL THEN 'paid'
            WHEN p.cancelled_at IS NOT NULL THEN 'cancelled'
            WHEN p.expired_at   IS NOT NULL THEN 'expired'
            ELSE 'pending' END AS state,
       b.booking_code AS booking_code,
       b.status       AS booking_status,
       sv.name        AS service_name,
       u.name         AS user_name,
       u.email        AS user_email
FROM payments p
JOIN bookings b  ON b.id  = p.booking_id
JOIN services sv ON sv.id = b.service_id
JOIN users    u  ON u.id  = b.user_id
WHERE FIND_IN_SET(
        CASE WHEN p.paid_at      IS NOT NULL THEN 'paid'
             WHEN p.cancelled_at IS NOT NULL THEN 'cancelled'
             WHEN p.expired_at   IS NOT NULL THEN 'expired'
             ELSE 'pending' END,
        ?) > 0
  AND p.created_at >= ? AND p.created_at <= ?
  AND (p.order_id     LIKE ?
    OR b.booking_code LIKE ?)
ORDER BY p.id ASC
LIMIT ?
`

type ListPaymentsForExportParams struct {
	StateList   string    `json:"state_list"`
	CreatedFrom time.Time `json:"created_from"`
	CreatedTo   time.Time `json:"created_to"`
	Search      string    `json:"search"`
	Limit       int32     `json:"limit"`
}

type ListPaymentsForExportRow struct {
	ID                int64          `json:"id"`
	OrderID           string         `json:"order_id"`
	GrossAmount       string         `json:"gross_amount"`
	PaymentType       sql.NullString `json:"payment_type"`
	TransactionID     sql.NullString `json:"transaction_id"`
	TransactionStatus sql.NullString `json:"transaction_status"`
	FraudStatus       sql.NullString `json:"fraud_status"`
	Bank              sql.NullString `json:"bank"`
	VaNumber          sql.NullString `json:"va_number"`
	PaidAt            sql.NullTime   `json:"paid_at"`
	ExpiredAt         sql.NullTime   `json:"expired_at"`
	CancelledAt       sql.NullTime   `json:"cancelled_at"`
	CreatedAt         time.Time      `json:"created_at"`
	State             string         `json:"state"`
	BookingCode       string         `json:"booking_code"`
	BookingStatus     BookingsStatus `json:"booking_status"`
	ServiceName       string         `json:"service_name"`
	UserName          string         `json:"user_name"`
	UserEmail         string         `json:"user_email"`
}

func (q *Queries) ListPaymentsForExport(ctx context.Context, arg ListPaymentsForExportParams) ([]ListPaymentsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsForExport,
		arg.StateList,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.Search,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsForExportRow{}
	for rows.Next() {
		var i ListPaymentsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.GrossAmount,
			&i.PaymentType,
			&i.TransactionID,
			&i.TransactionStatus,
			&i.FraudStatus,
			&i.Bank,
			&i.VaNumber,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.State,
			&i.BookingCode,
			&i.BookingStatus,
			&i.ServiceName,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPaidPayments = `-- name: ListRecentPaidPayments :many
SELECT p.id, p.order_id, p.gross_amount, p.payment_type, p.paid_at,
       b.booking_code AS booking_code,
       sv.name        AS service_name,
       u.name         AS user_name
FROM payments p
JOIN bookings b  ON b.id  = p.booking_id
JOIN services sv ON sv.id = b.service_id
JOIN users    u  ON u.id  = b.user_id
WHERE p.paid_at IS NOT NULL
ORDER BY p.paid_at DESC, p.id DESC
LIMIT ?
`

type ListRecentPaidPaymentsRow struct {
	ID          int64          `json:"id"`
	OrderID     string         `json:"order_id"`
	GrossAmount string         `json:"gross_amount"`
	PaymentType sql.NullString `json:"payment_type"`
	PaidAt      sql.NullTime   `json:"paid_at"`
	BookingCode string         `json:"booking_code"`
	ServiceName string         `json:"service_name"`
	UserName    string         `json:"user_name"`
}

// The dashboard's "pembayaran terbaru" card.
func (q *Queries) ListRecentPaidPayments(ctx context.Context, limit int32) ([]ListRecentPaidPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPaidPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentPaidPaymentsRow{}
	for rows.Next() {
		var i ListRecentPaidPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.GrossAmount,
			&i.PaymentType,
			&i.PaidAt,
			&i.BookingCode,
			&i.ServiceName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationProcessed = `-- name: MarkNotificationProcessed :exec
UPDATE payment_notifications SET processed = 1, process_note = ? WHERE id = ?
`

type MarkNotificationProcessedParams struct {
	ProcessNote sql.NullString `json:"process_note"`
	ID          int64          `json:"id"`
}

func (q *Queries) MarkNotificationProcessed(ctx context.Context, arg MarkNotificationProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationProcessed, arg.ProcessNote, arg.ID)
	return err
}

const markPaymentCancelled = `-- name: MarkPaymentCancelled :execresult
UPDATE payments SET
  transaction_status = ?,
  status_code        = ?,
  raw_response       = ?,
  cancelled_at       = NOW()
WHERE order_id = ? AND paid_at IS NULL AND expired_at IS NULL AND cancelled_at IS NULL
`

type MarkPaymentCancelledParams struct {
	TransactionStatus sql.NullString `json:"transaction_status"`
	StatusCode        sql.NullString `json:"status_code"`
	RawResponse       sql.NullString `json:"raw_response"`
	OrderID           string         `json:"order_id"`
}

// transaction_status = cancel.
func (q *Queries) MarkPaymentCancelled(ctx context.Context, arg MarkPaymentCancelledParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markPaymentCancelled,
		arg.TransactionStatus,
		arg.StatusCode,
		arg.RawResponse,
		arg.OrderID,
	)
}

const markPaymentExpired = `-- name: MarkPaymentExpired :execresult
UPDATE payments SET
  transaction_status = ?,
  fraud_status       = ?,
  status_code        = ?,
  raw_response       = ?,
  expired_at         = NOW()
WHERE order_id = ? AND paid_at IS NULL AND expired_at IS NULL AND cancelled_at IS NULL
`

type MarkPaymentExpiredParams struct {
	TransactionStatus sql.NullString `json:"transaction_status"`
	FraudStatus       sql.NullString `json:"fraud_status"`
	StatusCode        sql.NullString `json:"status_code"`
	RawResponse       sql.NullString `json:"raw_response"`
	OrderID           string         `json:"order_id"`
}

// transaction_status = deny or expire. The caller releases the slot iff this and
// the matching booking transition both report a real change.
func (q *Queries) MarkPaymentExpired(ctx context.Context, arg MarkPaymentExpiredParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markPaymentExpired,
		arg.TransactionStatus,
		arg.FraudStatus,
		arg.StatusCode,
		arg.RawResponse,
		arg.OrderID,
	)
}

const markPaymentPaid = `-- name: MarkPaymentPaid :execresult

UPDATE payments SET
  transaction_id     = ?,
  transaction_status = ?,
  transaction_time   = ?,
  payment_type       = ?,
  fraud_status       = ?,
  status_code        = ?,
  raw_response       = ?,
  paid_at            = NOW()
WHERE order_id = ? AND paid_at IS NULL AND expired_at IS NULL AND cancelled_at IS NULL
`

type MarkPaymentPaidParams struct {
	TransactionID     sql.NullString `json:"transaction_id"`
	TransactionStatus sql.NullString `json:"transaction_status"`
	TransactionTime   sql.NullTime   `json:"transaction_time"`
	PaymentType       sql.NullString `json:"payment_type"`
	FraudStatus       sql.NullString `json:"fraud_status"`
	StatusCode        sql.NullString `json:"status_code"`
	RawResponse       sql.NullString `json:"raw_response"`
	OrderID           string         `json:"order_id"`
}

// ---------------------------------------------------------------------------
// Idempotent transitions. Each is a no-op once any lifecycle timestamp is set.
// ---------------------------------------------------------------------------
// transaction_status = settlement, or capture + credit_card + fraud_status=accept.
func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markPaymentPaid,
		arg.TransactionID,
		arg.TransactionStatus,
		arg.TransactionTime,
		arg.PaymentType,
		arg.FraudStatus,
		arg.StatusCode,
		arg.RawResponse,
		arg.OrderID,
	)
}

const recordPaymentProgress = `-- name: RecordPaymentProgress :exec
UPDATE payments SET
  transaction_status = ?,
  transaction_id     = ?,
  transaction_time   = ?,
  payment_type       = ?,
  fraud_status       = ?,
  status_code        = ?,
  bank               = ?,
  va_number          = ?,
  raw_response       = ?
WHERE order_id = ? AND paid_at IS NULL
`

type RecordPaymentProgressParams struct {
	TransactionStatus sql.NullString `json:"transaction_status"`
	TransactionID     sql.NullString `json:"transaction_id"`
	TransactionTime   sql.NullTime   `json:"transaction_time"`
	PaymentType       sql.NullString `json:"payment_type"`
	FraudStatus       sql.NullString `json:"fraud_status"`
	StatusCode        sql.NullString `json:"status_code"`
	Bank              sql.NullString `json:"bank"`
	VaNumber          sql.NullString `json:"va_number"`
	RawResponse       sql.NullString `json:"raw_response"`
	OrderID           string         `json:"order_id"`
}

// transaction_status = pending, and capture + fraud_status = challenge. Records
// what Midtrans told us, moves no lifecycle timestamp, leaves the booking alone.
// A challenge is flagged for admin review rather than auto-accepted.
func (q *Queries) RecordPaymentProgress(ctx context.Context, arg RecordPaymentProgressParams) error {
	_, err := q.db.ExecContext(ctx, recordPaymentProgress,
		arg.TransactionStatus,
		arg.TransactionID,
		arg.TransactionTime,
		arg.PaymentType,
		arg.FraudStatus,
		arg.StatusCode,
		arg.Bank,
		arg.VaNumber,
		arg.RawResponse,
		arg.OrderID,
	)
	return err
}

const sumPaidBetween = `-- name: SumPaidBetween :one
SELECT CAST(COALESCE(SUM(gross_amount), 0) AS DECIMAL(14,2)) AS total,
       COUNT(*) AS paid_count
FROM payments
WHERE paid_at BETWEEN ? AND ?
`

type SumPaidBetweenParams struct {
	FromPaidAt sql.NullTime `json:"from_paid_at"`
	ToPaidAt   sql.NullTime `json:"to_paid_at"`
}

type SumPaidBetweenRow struct {
	Total     string `json:"total"`
	PaidCount int64  `json:"paid_count"`
}

// Dashboard revenue. The explicit CAST to DECIMAL is what makes sqlc type this
// as a Go string: a bare SUM(gross_amount) types as interface{}, and casting to
// CHAR does too. A string is also what keeps money off float64 all the way to
// util.Rupiah. COALESCE, because SUM over no rows is NULL, not 0.
func (q *Queries) SumPaidBetween(ctx context.Context, arg SumPaidBetweenParams) (SumPaidBetweenRow, error) {
	row := q.db.QueryRowContext(ctx, sumPaidBetween, arg.FromPaidAt, arg.ToPaidAt)
	var i SumPaidBetweenRow
	err := row.Scan(&i.Total, &i.PaidCount)
	return i, err
}

const updatePaymentSnap = `-- name: UpdatePaymentSnap :exec
UPDATE payments SET snap_token = ?, snap_redirect_url = ? WHERE id = ?
`

type UpdatePaymentSnapParams struct {
	SnapToken       sql.NullString `json:"snap_token"`
	SnapRedirectUrl sql.NullString `json:"snap_redirect_url"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdatePaymentSnap(ctx context.Context, arg UpdatePaymentSnapParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentSnap, arg.SnapToken, arg.SnapRedirectUrl, arg.ID)
	return err
}
