// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddTherapistService(ctx context.Context, arg AddTherapistServiceParams) error
	BookingCodeTaken(ctx context.Context, bookingCode string) (bool, error)
	// Releases the slot: the caller must call ReleaseSlot iff RowsAffected() == 1.
	CancelBooking(ctx context.Context, arg CancelBookingParams) (sql.Result, error)
	// Phase 9 user-initiated cancellation. Narrower guard than CancelBooking, with
	// ownership enforced in the WHERE rather than trusted from the handler.
	// Releases the slot: ReleaseSlot iff RowsAffected() == 1.
	CancelPendingBookingByOwner(ctx context.Context, arg CancelPendingBookingByOwnerParams) (sql.Result, error)
	CompleteBooking(ctx context.Context, id int64) (sql.Result, error)
	ConfirmBooking(ctx context.Context, id int64) (sql.Result, error)
	// The last-admin guard: demoting or deactivating the only remaining admin locks
	// everyone out of the panel, and TPJ owns no credentials to get back in with.
	CountActiveAdmins(ctx context.Context) (int64, error)
	// How many slots in a range a bulk delete will refuse to touch.
	//
	// DeleteUnbookedSlotsInRange reports what it deleted but not what it left
	// alone, so without this the admin is told "12 dihapus" with no hint that 3
	// booked slots survived. Run it before the delete, in the same request.
	CountBookedSlotsInRange(ctx context.Context, arg CountBookedSlotsInRangeParams) (int64, error)
	CountBookingsAdmin(ctx context.Context, arg CountBookingsAdminParams) (int64, error)
	// The dashboard's counts by status, over a slot-date range.
	CountBookingsByStatusInRange(ctx context.Context, arg CountBookingsByStatusInRangeParams) ([]CountBookingsByStatusInRangeRow, error)
	CountBookingsByUser(ctx context.Context, arg CountBookingsByUserParams) (int64, error)
	// The admin panel calls this before offering delete.
	CountBookingsForService(ctx context.Context, serviceID int64) (int64, error)
	// Shown on the user list, so an operator can see whether a row is a real
	// customer before deactivating it.
	CountBookingsForUser(ctx context.Context, userID int64) (int64, error)
	CountPaymentsAdmin(ctx context.Context, arg CountPaymentsAdminParams) (int64, error)
	CountServicesAdmin(ctx context.Context, search string) (int64, error)
	// The invariant: this must always equal schedule_slots.booked_count. Asserted by
	// the Phase 13 concurrency tests.
	CountSlotHoldingBookings(ctx context.Context, slotID int64) (int64, error)
	// How many slots a date range holds, without pulling them. The admin calendar
	// uses it to decide whether a range is worth rendering at all.
	CountSlotsInRange(ctx context.Context, arg CountSlotsInRangeParams) (int64, error)
	CountTherapistsAdmin(ctx context.Context, search string) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	// activity_logs — audit trail for admin actions and booking state changes.
	// meta is a JSON column: pass NULL or valid JSON, never an empty string.
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error
	// bookings — the booking lifecycle.
	//
	// Slot-holding statuses: pending_payment, paid, confirmed, completed.
	// Slot-releasing statuses: cancelled, expired.
	//
	// EVERY status transition below is :execresult and guarded by the current
	// status. RowsAffected() == 1 IS the definition of "a real status transition",
	// and is the only thing that authorises a ReleaseSlot call. RowsAffected() == 0
	// means the transition was already applied — a Midtrans retry, a double-clicked
	// button, the expiry ticker racing the webhook — in which case do nothing else
	// and report success.
	// active_slot_id is a generated column and must not appear in the column list.
	CreateBooking(ctx context.Context, arg CreateBookingParams) (sql.Result, error)
	// payments and payment_notifications — the Midtrans side.
	//
	// Payment is confirmed ONLY by the webhook (PLAN.md R7). A successful Snap token
	// response is not a purchase.
	//
	// Midtrans retries notifications, and a retry can arrive while the first is
	// still in flight. Every transition below is guarded so that re-applying a
	// notification affects 0 rows: RowsAffected() == 0 means "already applied",
	// which must return 200 and change nothing else.
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error)
	// ---------------------------------------------------------------------------
	// Webhook audit log
	// ---------------------------------------------------------------------------
	// Written BEFORE any validation or processing, for every inbound payload —
	// including invalid signatures and order IDs belonging to other Appskep systems
	// on the shared merchant account. gross_amount is stored as the exact string
	// received because it is an input to the SHA512 signature.
	CreatePaymentNotification(ctx context.Context, arg CreatePaymentNotificationParams) (sql.Result, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (sql.Result, error)
	CreateSlot(ctx context.Context, arg CreateSlotParams) (sql.Result, error)
	// The Phase 5 generator. RowsAffected() == 0 means "already existed, skipped" —
	// that is the created/skipped counter, and what makes a re-run a no-op.
	CreateSlotIfAbsent(ctx context.Context, arg CreateSlotIfAbsentParams) (sql.Result, error)
	CreateTherapist(ctx context.Context, arg CreateTherapistParams) (sql.Result, error)
	// Blocked by fk_bookings_service (RESTRICT) once any booking references it. The
	// handler checks CountBookingsForService first and offers deactivation instead.
	DeleteService(ctx context.Context, id int64) (sql.Result, error)
	DeleteSetting(ctx context.Context, settingKey string) error
	// RowsAffected() == 0 means the slot had bookings and was left alone.
	DeleteSlotIfUnbooked(ctx context.Context, id int64) (sql.Result, error)
	// Nothing references a therapist except therapist_services, which CASCADEs, so
	// unlike DeleteService this can never be blocked by a foreign key.
	DeleteTherapist(ctx context.Context, id int64) (sql.Result, error)
	DeleteTherapistServices(ctx context.Context, therapistID int64) error
	DeleteUnbookedSlotsInRange(ctx context.Context, arg DeleteUnbookedSlotsInRangeParams) (sql.Result, error)
	// Releases the slot: the caller must call ReleaseSlot iff RowsAffected() == 1.
	ExpireBooking(ctx context.Context, id int64) (sql.Result, error)
	// The public detail page. Inactive services must 404, not render.
	GetActiveServiceBySlug(ctx context.Context, slug string) (Service, error)
	// The public profile page. Inactive therapists must 404, not render.
	GetActiveTherapistBySlug(ctx context.Context, slug string) (Therapist, error)
	GetBooking(ctx context.Context, id int64) (Booking, error)
	// Everything the admin detail page renders, in one round trip. The customer's
	// own page uses GetBookingDetailByCode; this one is by id, carries the slot's
	// capacity and the local user record, and has no ownership predicate — the route
	// is behind RequireAdmin.
	GetBookingAdminDetail(ctx context.Context, id int64) (GetBookingAdminDetailRow, error)
	GetBookingByCode(ctx context.Context, bookingCode string) (Booking, error)
	GetBookingByCodeForUpdate(ctx context.Context, bookingCode string) (Booking, error)
	// The konfirmasi / pembayaran pages: everything needed to render in one round
	// trip.
	GetBookingDetailByCode(ctx context.Context, bookingCode string) (GetBookingDetailByCodeRow, error)
	// If this transaction will also change booked_count, take GetSlotForUpdate
	// first (see the lock order note in schedules.sql).
	GetBookingForUpdate(ctx context.Context, id int64) (Booking, error)
	// What this customer told us last time, to prefill the next booking form with.
	//
	// Any status: a cancelled or expired booking still recorded where this person
	// lives and how to reach them. ORDER BY id, not created_at — id is the primary
	// key and strictly increasing, so two bookings made in the same second cannot
	// tie and pick an arbitrary winner.
	GetLatestBookingContactByUser(ctx context.Context, userID int64) (GetLatestBookingContactByUserRow, error)
	GetLatestPaymentForBooking(ctx context.Context, bookingID int64) (Payment, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetPaymentAdminDetail(ctx context.Context, id int64) (GetPaymentAdminDetailRow, error)
	GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error)
	// The webhook entry point. This lock, plus the guarded UPDATEs below, is what
	// makes the notification state machine idempotent under concurrent retries.
	GetPaymentByOrderIDForUpdate(ctx context.Context, orderID string) (Payment, error)
	// create-order.md:93 — repeated taps of "Bayar sekarang" must return the SAME
	// Snap URL rather than minting a new order_id on the shared merchant account.
	//
	// The "still within the booking's expires_at" leg of the rule is applied in Go
	// against the already-loaded booking row, which keeps every parameter here
	// directly comparable to a bare column.
	GetReusablePaymentForBooking(ctx context.Context, arg GetReusablePaymentForBookingParams) (Payment, error)
	// services — the layanan catalogue.
	GetService(ctx context.Context, id int64) (Service, error)
	GetServiceBySlug(ctx context.Context, slug string) (Service, error)
	// settings — key/value site configuration, editable from /admin/pengaturan.
	//
	// Where a key also exists in the environment (payment_expiry_minutes vs
	// PAYMENT_EXPIRY_MINUTES), the DB row wins when present and parseable; the env
	// value is the fallback and the fail-fast default. config stays the only reader
	// of os.Getenv.
	GetSetting(ctx context.Context, settingKey string) (sql.NullString, error)
	// schedule_slots — bookable time slots, and the slot side of the concurrency
	// design.
	//
	// CANONICAL LOCK ORDER: schedule_slots -> bookings -> payments.
	// Any transaction that will change a slot's booked_count must take that slot's
	// FOR UPDATE lock FIRST, before locking any booking or payment row. Booking
	// creation naturally locks slot-then-booking; a naive expiry ticker would lock
	// booking-then-slot, and the two together deadlock.
	GetSlot(ctx context.Context, id int64) (ScheduleSlot, error)
	// THE lock. This must be the first statement of the booking transaction, taken
	// BEFORE the capacity check — not after. That ordering is the entire reason two
	// concurrent bookings on a capacity-1 slot cannot both succeed: the second
	// request blocks here until the first commits, and then correctly sees the slot
	// as full. See PLAN.md § Design note: slot concurrency.
	GetSlotForUpdate(ctx context.Context, id int64) (ScheduleSlot, error)
	// Pre-flight duplicate check, so the user gets a friendly message instead of a
	// constraint error. It is only a nicety: the real guarantee is the unique index
	// uq_bookings_active_slot_user, which cannot be bypassed by application code.
	GetSlotHoldingBookingForUser(ctx context.Context, arg GetSlotHoldingBookingForUserParams) (Booking, error)
	// therapists — the terapis profiles, and which layanan each one handles.
	GetTherapist(ctx context.Context, id int64) (Therapist, error)
	// users — the local mirror of the Appskep identity.
	//
	// Nothing here authenticates anyone. Identity comes from the Appskep JWT; these
	// queries only keep the local mirror in step with it.
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByAppskepID(ctx context.Context, appskepUserID uint64) (User, error)
	// Whether the public site advertises the terapis section at all. EXISTS rather
	// than a COUNT: the answer is a yes/no, and idx_therapists_active_sort makes it
	// an index-only lookup.
	HasActiveTherapists(ctx context.Context) (bool, error)
	// The increment. Runs inside the booking transaction, after GetSlotForUpdate.
	//
	// The WHERE clause is defence in depth, not the primary safety mechanism — the
	// row lock is what makes this correct. RowsAffected() == 0 means the slot filled
	// or was deactivated between page load and submit; render "slot baru saja
	// terisi" back into the Turbo Frame rather than an error page.
	HoldSlot(ctx context.Context, id int64) (sql.Result, error)
	// Public listing. Includes coming-soon services: they are shown with a label.
	ListActiveServices(ctx context.Context) ([]Service, error)
	// Public listing.
	ListActiveTherapists(ctx context.Context) ([]Therapist, error)
	// The reverse link, for the strip on /layanan/{slug}.
	ListActiveTherapistsForService(ctx context.Context, serviceID int64) ([]Therapist, error)
	ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]ActivityLog, error)
	// The booking detail timeline in the admin panel.
	ListActivityLogsForEntity(ctx context.Context, arg ListActivityLogsForEntityParams) ([]ActivityLog, error)
	// The date picker: which dates still have at least one free slot.
	ListAvailableDates(ctx context.Context, arg ListAvailableDatesParams) ([]ListAvailableDatesRow, error)
	// The public availability query (booking step 2, loaded into a Turbo Frame).
	// `starts_at >= ?` receives now + booking_lead_time_minutes, computed in Go, so
	// past and too-soon slots disappear without an INTERVAL expression that sqlc
	// cannot type.
	//
	// There is no service_id predicate: every slot is global today (PLAN.md Q4), so
	// it would always be true while costing a nullable parameter at every call site.
	// It gets added in the same change that flips Q4.
	ListAvailableSlotsByDate(ctx context.Context, arg ListAvailableSlotsByDateParams) ([]ScheduleSlot, error)
	// Booking step 1. Coming-soon services appear on the public site but cannot be
	// booked, so they are excluded here.
	ListBookableServices(ctx context.Context) ([]Service, error)
	// ---------------------------------------------------------------------------
	// Admin panel (Phase 10)
	//
	// One WHERE clause serves every filter combination, following the same
	// techniques as ListBookingsByUser above: a comma-joined status list through
	// FIND_IN_SET (sqlc's MySQL engine has no sqlc.slice()), "%" for an empty search
	// box, and a 0 sentinel for "any layanan".
	//
	// BOTH date ranges are always applied, and the caller widens the one the
	// operator did not choose (?tanggal=jadwal|dibuat). That is not a style
	// preference. sqlc's MySQL engine mis-binds BETWEEN here in two different ways,
	// and each produces SQL whose placeholder count does not match the generated
	// call — a runtime failure on the first request, invisible at generate time:
	//
	//   * `(CASE ... END) BETWEEN ? AND ?` and `DATE(created_at) BETWEEN ? AND ?`
	//     emit the placeholders but DROP both parameters. An expression on the left
	//     of BETWEEN is not bound at all.
	//   * `b.created_at BETWEEN ? AND ?` DUPLICATES each parameter once per joined
	//     table that also has a created_at column — four copies here, table
	//     qualifier ignored.
	//
	// `col >= ? AND col <= ?` binds correctly in every case, and is what all three
	// admin queries below use. Two plain columns are also index-friendly, which the
	// CASE form was not.
	//
	// created_at is a DATETIME, so the caller passes an end-of-day instant for the
	// upper bound; a bare date there would cut at midnight and hide the last day.
	// ---------------------------------------------------------------------------
	// Schedule order, direction chosen by a parameter rather than by a second
	// near-identical query. The unused branch evaluates to a constant NULL, which
	// orders nothing. Ordering is always by the slot's instant, whichever date the
	// operator filtered on: this list is a day sheet, and reading it in schedule
	// order is what an operator is doing with it.
	//
	// oldest_first types as interface{} — sqlc's MySQL engine cannot infer a Go type
	// for a parameter compared against a literal. Wrapping it in CAST(... AS
	// UNSIGNED) does type it, but as TWO separate int64 fields that a caller could
	// set to disagreeing values and silently get a wrong order; one untyped field
	// bound twice cannot disagree with itself. The single caller passes 0 or 1.
	ListBookingsAdmin(ctx context.Context, arg ListBookingsAdminParams) ([]ListBookingsAdminRow, error)
	// The dashboard day sheet: who is coming on one date, in time order. Released
	// bookings are excluded — a cancelled booking is not on today's list.
	ListBookingsBySlotDate(ctx context.Context, slotDate time.Time) ([]ListBookingsBySlotDateRow, error)
	// Halaman riwayat. Pass a comma-joined status list; for "all", pass
	// "pending_payment,paid,confirmed,completed,cancelled,expired".
	//
	// FIND_IN_SET avoids sqlc.slice(), which the MySQL engine does not support. The
	// CAST is required: an ENUM in a numeric context yields its ordinal, not its
	// label, so FIND_IN_SET would silently match the wrong rows without it.
	ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error)
	// The CSV export. Same predicate as the list, no OFFSET, and a LIMIT the service
	// sets so an export cannot pull an unbounded result set into memory.
	ListBookingsForExport(ctx context.Context, arg ListBookingsForExportParams) ([]ListBookingsForExportRow, error)
	// The Phase 11 H-1 reminder sweep's work queue: bookings on one slot date that
	// are still coming and have not been reminded yet.
	//
	// 'paid' as well as 'confirmed': confirming is an operator action that may never
	// happen, and a customer who has paid is coming regardless. 'completed' is
	// excluded because a completed booking is in the past by definition.
	//
	// Only the id is needed — the worker re-reads the whole booking through
	// GetBookingAdminDetail at send time, so a reminder describes the booking as it
	// is when it goes out rather than as it was when it was queued.
	ListBookingsForReminder(ctx context.Context, arg ListBookingsForReminderParams) ([]int64, error)
	// ---------------------------------------------------------------------------
	// Lists
	// ---------------------------------------------------------------------------
	// The Phase 7 expiry ticker's work queue. slot_id is selected so the worker can
	// take the SLOT lock first, preserving the canonical lock order.
	//
	// NOW() rather than a timestamp passed from Go: one clock decides expiry, so
	// app-server clock skew cannot expire bookings early or leak slots.
	ListExpiredPendingBookings(ctx context.Context, limit int32) ([]ListExpiredPendingBookingsRow, error)
	// The Phase 10 reschedule picker: every slot with room left, between two
	// instants.
	//
	// It deliberately does NOT apply booking_lead_time_minutes. That rule protects a
	// customer from booking themselves into a slot the clinic cannot prepare for; an
	// admin moving someone to a slot half an hour out is a phone call, not a
	// mistake. The caller passes `now` as the lower bound, so a slot that has
	// already started is still excluded.
	ListFreeSlotsBetween(ctx context.Context, arg ListFreeSlotsBetweenParams) ([]ScheduleSlot, error)
	ListPaymentNotificationsByOrderID(ctx context.Context, orderID string) ([]PaymentNotification, error)
	// ---------------------------------------------------------------------------
	// Admin panel (Phase 10)
	//
	// A payment has no status column on purpose (see the schema comment): its
	// lifecycle is paid_at / expired_at / cancelled_at. The list filter therefore
	// runs against a derived state, and the same CASE is selected so the page can
	// label a row without re-deriving the rule in Go.
	//
	// The date range is `>= ? AND <= ?` on a bare column, never
	// `DATE(p.created_at) BETWEEN ? AND ?`. See the note in bookings.sql: sqlc's
	// MySQL engine mis-binds BETWEEN in both directions here, and only the
	// comparison form generates a call whose argument count matches its SQL. The
	// caller passes an end-of-day instant for the upper bound, since created_at is a
	// DATETIME.
	// ---------------------------------------------------------------------------
	ListPaymentsAdmin(ctx context.Context, arg ListPaymentsAdminParams) ([]ListPaymentsAdminRow, error)
	ListPaymentsForBooking(ctx context.Context, bookingID int64) ([]Payment, error)
	ListPaymentsForExport(ctx context.Context, arg ListPaymentsForExportParams) ([]ListPaymentsForExportRow, error)
	// The dashboard's "pembayaran terbaru" card.
	ListRecentPaidPayments(ctx context.Context, limit int32) ([]ListRecentPaidPaymentsRow, error)
	// Drives the admin form's checkbox state. Deliberately unfiltered: a tag
	// pointing at a deactivated layanan must still be visible to the service layer,
	// which decides what to do with it.
	ListServiceIDsForTherapist(ctx context.Context, therapistID int64) ([]int64, error)
	// One query for the whole /terapis grid, grouped by therapist_id in Go. The
	// alternative is a ListServicesForTherapist per card.
	ListServiceTagsForActiveTherapists(ctx context.Context) ([]ListServiceTagsForActiveTherapistsRow, error)
	// Pass "%" for an empty search box.
	ListServicesAdmin(ctx context.Context, arg ListServicesAdminParams) ([]Service, error)
	// ---------------------------------------------------------------------------
	// therapist_services
	// ---------------------------------------------------------------------------
	// The public profile page. Active layanan only, in the catalogue's own order.
	ListServicesForTherapist(ctx context.Context, therapistID int64) ([]Service, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	// The admin calendar / list view.
	ListSlotsByDateRange(ctx context.Context, arg ListSlotsByDateRangeParams) ([]ScheduleSlot, error)
	// Pass "%" for an empty search box.
	ListTherapistsAdmin(ctx context.Context, arg ListTherapistsAdminParams) ([]Therapist, error)
	// Pass "%" for an empty search box: name and email are NOT NULL, so LIKE '%'
	// matches every row and no SQL branching is needed.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// ---------------------------------------------------------------------------
	// Status transitions
	// ---------------------------------------------------------------------------
	// Applied only by the Midtrans webhook (settlement, or capture + credit_card +
	// fraud_status=accept). Never from a Snap token response or a client callback.
	MarkBookingPaid(ctx context.Context, id int64) (sql.Result, error)
	// Claims one booking for the reminder sweep. RowsAffected() == 1 is the only
	// thing that authorises sending the email — the same rule that guards every
	// status transition above. Claim-then-send is deliberate: a duplicate reminder
	// is worse than a missing one, so a send that fails afterwards is not retried.
	MarkBookingReminderSent(ctx context.Context, id int64) (sql.Result, error)
	MarkNotificationProcessed(ctx context.Context, arg MarkNotificationProcessedParams) error
	// transaction_status = cancel.
	MarkPaymentCancelled(ctx context.Context, arg MarkPaymentCancelledParams) (sql.Result, error)
	// transaction_status = deny or expire. The caller releases the slot iff this and
	// the matching booking transition both report a real change.
	MarkPaymentExpired(ctx context.Context, arg MarkPaymentExpiredParams) (sql.Result, error)
	// ---------------------------------------------------------------------------
	// Idempotent transitions. Each is a no-op once any lifecycle timestamp is set.
	// ---------------------------------------------------------------------------
	// transaction_status = settlement, or capture + credit_card + fraud_status=accept.
	MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (sql.Result, error)
	// transaction_status = pending, and capture + fraud_status = challenge. Records
	// what Midtrans told us, moves no lifecycle timestamp, leaves the booking alone.
	// A challenge is flagged for admin review rather than auto-accepted.
	RecordPaymentProgress(ctx context.Context, arg RecordPaymentProgressParams) error
	// Repair tool for the admin panel and tests. Not part of any normal write path;
	// if this ever changes a row in production, something upstream is broken.
	RecountSlotBooked(ctx context.Context, id int64) error
	// The guarded decrement. The CALLER must have observed a real status transition
	// first — RowsAffected() == 1 from ExpireBooking or CancelBooking — inside the
	// same transaction. Never call this unconditionally: the expiry ticker and the
	// Midtrans webhook can both reach the same booking, and only the one that
	// actually moved the status may release the slot.
	//
	// GREATEST(..., 0) means even a logic error cannot drive the counter negative.
	ReleaseSlot(ctx context.Context, id int64) error
	// Phase 10. The caller must decrement the old slot and increment the new one in
	// the same transaction, taking both slot locks in ascending id order.
	RescheduleBooking(ctx context.Context, arg RescheduleBookingParams) (sql.Result, error)
	// Pass 0 as the id when creating, so no row is excluded.
	ServiceSlugTaken(ctx context.Context, arg ServiceSlugTakenParams) (bool, error)
	SetServiceActive(ctx context.Context, arg SetServiceActiveParams) error
	SetServiceComingSoon(ctx context.Context, arg SetServiceComingSoonParams) error
	SetSlotActive(ctx context.Context, arg SetSlotActiveParams) error
	SetSlotActiveInRange(ctx context.Context, arg SetSlotActiveInRangeParams) (sql.Result, error)
	SetTherapistActive(ctx context.Context, arg SetTherapistActiveParams) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	// Dashboard revenue. The explicit CAST to DECIMAL is what makes sqlc type this
	// as a Go string: a bare SUM(gross_amount) types as interface{}, and casting to
	// CHAR does too. A string is also what keeps money off float64 all the way to
	// util.Rupiah. COALESCE, because SUM over no rows is NULL, not 0.
	SumPaidBetween(ctx context.Context, arg SumPaidBetweenParams) (SumPaidBetweenRow, error)
	// Pass 0 as the id when creating, so no row is excluded.
	TherapistSlugTaken(ctx context.Context, arg TherapistSlugTakenParams) (bool, error)
	// The only booking field an admin may edit freely. Everything else is either a
	// status transition or a reschedule, both of which move a slot.
	UpdateBookingNotes(ctx context.Context, arg UpdateBookingNotesParams) error
	UpdatePaymentSnap(ctx context.Context, arg UpdatePaymentSnapParams) error
	// image_path is updated separately so a form submit without a new file cannot
	// blank an existing image.
	UpdateService(ctx context.Context, arg UpdateServiceParams) error
	UpdateServiceImage(ctx context.Context, arg UpdateServiceImageParams) error
	// Lowering capacity below booked_count violates chk_slots_count and surfaces as
	// a constraint error, which the handler renders as "kapasitas tidak boleh lebih
	// kecil dari jumlah booking".
	//
	// is_active is written here as well as by SetSlotActive: the edit form owns the
	// flag alongside every other field, and leaving it out would make saving the
	// form silently discard a status change the admin just made.
	UpdateSlot(ctx context.Context, arg UpdateSlotParams) error
	// image_path is updated separately so a form submit without a new file cannot
	// blank an existing photo. slug is absent for the same reason it is absent from
	// UpdateService: it is the public URL and is allocated once, at creation.
	UpdateTherapist(ctx context.Context, arg UpdateTherapistParams) error
	UpdateTherapistImage(ctx context.Context, arg UpdateTherapistImageParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	// Runs only after the Appskep account API has accepted the same values, so it
	// mirrors what Appskep now holds. name/email/phone/birthdate/sex are
	// Appskep-owned and pushed there first; address/latitude/longitude are local.
	//
	// latitude and longitude move as a pair, always both, so clearing the map pin
	// cannot leave half of one behind.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	// Called on every login. Refreshes the Appskep-owned fields and stamps the
	// login. It deliberately does NOT touch `role`: an admin demoted in the Phase 10
	// user panel must stay demoted through their next login. Bootstrap promotion
	// from ADMIN_USER_IDS is a separate SetUserRole call.
	UpsertUserFromSSO(ctx context.Context, arg UpsertUserFromSSOParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
