// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countBookedSlotsInRange = `-- name: CountBookedSlotsInRange :one
SELECT COUNT(*) AS total FROM schedule_slots
WHERE slot_date BETWEEN ? AND ? AND booked_count > 0
`

type CountBookedSlotsInRangeParams struct {
	FromSlotDate time.Time `json:"from_slot_date"`
	ToSlotDate   time.Time `json:"to_slot_date"`
}

// How many slots in a range a bulk delete will refuse to touch.
//
// DeleteUnbookedSlotsInRange reports what it deleted but not what it left
// alone, so without this the admin is told "12 dihapus" with no hint that 3
// booked slots survived. Run it before the delete, in the same request.
func (q *Queries) CountBookedSlotsInRange(ctx context.Context, arg CountBookedSlotsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookedSlotsInRange, arg.FromSlotDate, arg.ToSlotDate)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSlotHoldingBookings = `-- name: CountSlotHoldingBookings :one
SELECT COUNT(*) AS total FROM bookings
WHERE slot_id = ? AND status NOT IN ('cancelled', 'expired')
`

// The invariant: this must always equal schedule_slots.booked_count. Asserted by
// the Phase 13 concurrency tests.
func (q *Queries) CountSlotHoldingBookings(ctx context.Context, slotID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSlotHoldingBookings, slotID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSlotsInRange = `-- name: CountSlotsInRange :one
SELECT COUNT(*) AS total FROM schedule_slots WHERE slot_date BETWEEN ? AND ?
`

type CountSlotsInRangeParams struct {
	FromSlotDate time.Time `json:"from_slot_date"`
	ToSlotDate   time.Time `json:"to_slot_date"`
}

// How many slots a date range holds, without pulling them. The admin calendar
// uses it to decide whether a range is worth rendering at all.
func (q *Queries) CountSlotsInRange(ctx context.Context, arg CountSlotsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSlotsInRange, arg.FromSlotDate, arg.ToSlotDate)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSlot = `-- name: CreateSlot :execresult
INSERT INTO schedule_slots (service_id, slot_date, start_time, end_time, capacity, is_active, note)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSlotParams struct {
	ServiceID sql.NullInt64  `json:"service_id"`
	SlotDate  time.Time      `json:"slot_date"`
	StartTime string         `json:"start_time"`
	EndTime   string         `json:"end_time"`
	Capacity  int32          `json:"capacity"`
	IsActive  bool           `json:"is_active"`
	Note      sql.NullString `json:"note"`
}

func (q *Queries) CreateSlot(ctx context.Context, arg CreateSlotParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSlot,
		arg.ServiceID,
		arg.SlotDate,
		arg.StartTime,
		arg.EndTime,
		arg.Capacity,
		arg.IsActive,
		arg.Note,
	)
}

const createSlotIfAbsent = `-- name: CreateSlotIfAbsent :execresult
INSERT IGNORE INTO schedule_slots (service_id, slot_date, start_time, end_time, capacity, is_active, note)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSlotIfAbsentParams struct {
	ServiceID sql.NullInt64  `json:"service_id"`
	SlotDate  time.Time      `json:"slot_date"`
	StartTime string         `json:"start_time"`
	EndTime   string         `json:"end_time"`
	Capacity  int32          `json:"capacity"`
	IsActive  bool           `json:"is_active"`
	Note      sql.NullString `json:"note"`
}

// The Phase 5 generator. RowsAffected() == 0 means "already existed, skipped" —
// that is the created/skipped counter, and what makes a re-run a no-op.
func (q *Queries) CreateSlotIfAbsent(ctx context.Context, arg CreateSlotIfAbsentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSlotIfAbsent,
		arg.ServiceID,
		arg.SlotDate,
		arg.StartTime,
		arg.EndTime,
		arg.Capacity,
		arg.IsActive,
		arg.Note,
	)
}

const deleteSlotIfUnbooked = `-- name: DeleteSlotIfUnbooked :execresult
DELETE FROM schedule_slots WHERE id = ? AND booked_count = 0
`

// RowsAffected() == 0 means the slot had bookings and was left alone.
func (q *Queries) DeleteSlotIfUnbooked(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSlotIfUnbooked, id)
}

const deleteUnbookedSlotsInRange = `-- name: DeleteUnbookedSlotsInRange :execresult
DELETE FROM schedule_slots WHERE slot_date BETWEEN ? AND ? AND booked_count = 0
`

type DeleteUnbookedSlotsInRangeParams struct {
	FromSlotDate time.Time `json:"from_slot_date"`
	ToSlotDate   time.Time `json:"to_slot_date"`
}

func (q *Queries) DeleteUnbookedSlotsInRange(ctx context.Context, arg DeleteUnbookedSlotsInRangeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUnbookedSlotsInRange, arg.FromSlotDate, arg.ToSlotDate)
}

const getSlot = `-- name: GetSlot :one

SELECT id, service_id, slot_date, start_time, end_time, starts_at, ends_at, capacity, booked_count, is_active, note, created_at, updated_at FROM schedule_slots WHERE id = ? LIMIT 1
`

// schedule_slots — bookable time slots, and the slot side of the concurrency
// design.
//
// CANONICAL LOCK ORDER: schedule_slots -> bookings -> payments.
// Any transaction that will change a slot's booked_count must take that slot's
// FOR UPDATE lock FIRST, before locking any booking or payment row. Booking
// creation naturally locks slot-then-booking; a naive expiry ticker would lock
// booking-then-slot, and the two together deadlock.
func (q *Queries) GetSlot(ctx context.Context, id int64) (ScheduleSlot, error) {
	row := q.db.QueryRowContext(ctx, getSlot, id)
	var i ScheduleSlot
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.SlotDate,
		&i.StartTime,
		&i.EndTime,
		&i.StartsAt,
		&i.EndsAt,
		&i.Capacity,
		&i.BookedCount,
		&i.IsActive,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlotForUpdate = `-- name: GetSlotForUpdate :one
SELECT id, service_id, slot_date, start_time, end_time, starts_at, ends_at, capacity, booked_count, is_active, note, created_at, updated_at FROM schedule_slots WHERE id = ? FOR UPDATE
`

// THE lock. This must be the first statement of the booking transaction, taken
// BEFORE the capacity check — not after. That ordering is the entire reason two
// concurrent bookings on a capacity-1 slot cannot both succeed: the second
// request blocks here until the first commits, and then correctly sees the slot
// as full. See PLAN.md § Design note: slot concurrency.
func (q *Queries) GetSlotForUpdate(ctx context.Context, id int64) (ScheduleSlot, error) {
	row := q.db.QueryRowContext(ctx, getSlotForUpdate, id)
	var i ScheduleSlot
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.SlotDate,
		&i.StartTime,
		&i.EndTime,
		&i.StartsAt,
		&i.EndsAt,
		&i.Capacity,
		&i.BookedCount,
		&i.IsActive,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const holdSlot = `-- name: HoldSlot :execresult
UPDATE schedule_slots SET booked_count = booked_count + 1
WHERE id = ? AND is_active = 1 AND booked_count < capacity
`

// The increment. Runs inside the booking transaction, after GetSlotForUpdate.
//
// The WHERE clause is defence in depth, not the primary safety mechanism — the
// row lock is what makes this correct. RowsAffected() == 0 means the slot filled
// or was deactivated between page load and submit; render "slot baru saja
// terisi" back into the Turbo Frame rather than an error page.
func (q *Queries) HoldSlot(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, holdSlot, id)
}

const listAvailableDates = `-- name: ListAvailableDates :many
SELECT slot_date, COUNT(*) AS free_slots
FROM schedule_slots
WHERE is_active    = 1
  AND booked_count < capacity
  AND starts_at   >= ?
  AND slot_date   <= ?
GROUP BY slot_date
ORDER BY slot_date ASC
`

type ListAvailableDatesParams struct {
	StartsAt time.Time `json:"starts_at"`
	SlotDate time.Time `json:"slot_date"`
}

type ListAvailableDatesRow struct {
	SlotDate  time.Time `json:"slot_date"`
	FreeSlots int64     `json:"free_slots"`
}

// The date picker: which dates still have at least one free slot.
func (q *Queries) ListAvailableDates(ctx context.Context, arg ListAvailableDatesParams) ([]ListAvailableDatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableDates, arg.StartsAt, arg.SlotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableDatesRow{}
	for rows.Next() {
		var i ListAvailableDatesRow
		if err := rows.Scan(&i.SlotDate, &i.FreeSlots); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableSlotsByDate = `-- name: ListAvailableSlotsByDate :many
SELECT id, service_id, slot_date, start_time, end_time, starts_at, ends_at, capacity, booked_count, is_active, note, created_at, updated_at FROM schedule_slots
WHERE slot_date    = ?
  AND is_active    = 1
  AND booked_count < capacity
  AND starts_at   >= ?
ORDER BY start_time ASC
`

type ListAvailableSlotsByDateParams struct {
	SlotDate time.Time `json:"slot_date"`
	StartsAt time.Time `json:"starts_at"`
}

// The public availability query (booking step 2, loaded into a Turbo Frame).
// `starts_at >= ?` receives now + booking_lead_time_minutes, computed in Go, so
// past and too-soon slots disappear without an INTERVAL expression that sqlc
// cannot type.
//
// There is no service_id predicate: every slot is global today (PLAN.md Q4), so
// it would always be true while costing a nullable parameter at every call site.
// It gets added in the same change that flips Q4.
func (q *Queries) ListAvailableSlotsByDate(ctx context.Context, arg ListAvailableSlotsByDateParams) ([]ScheduleSlot, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableSlotsByDate, arg.SlotDate, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleSlot{}
	for rows.Next() {
		var i ScheduleSlot
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SlotDate,
			&i.StartTime,
			&i.EndTime,
			&i.StartsAt,
			&i.EndsAt,
			&i.Capacity,
			&i.BookedCount,
			&i.IsActive,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreeSlotsBetween = `-- name: ListFreeSlotsBetween :many
SELECT id, service_id, slot_date, start_time, end_time, starts_at, ends_at, capacity, booked_count, is_active, note, created_at, updated_at FROM schedule_slots
WHERE is_active    = 1
  AND booked_count < capacity
  AND starts_at BETWEEN ? AND ?
ORDER BY starts_at ASC
LIMIT ?
`

type ListFreeSlotsBetweenParams struct {
	FromStartsAt sql.NullTime `json:"from_starts_at"`
	ToStartsAt   sql.NullTime `json:"to_starts_at"`
	Limit        int32        `json:"limit"`
}

// The Phase 10 reschedule picker: every slot with room left, between two
// instants.
//
// It deliberately does NOT apply booking_lead_time_minutes. That rule protects a
// customer from booking themselves into a slot the clinic cannot prepare for; an
// admin moving someone to a slot half an hour out is a phone call, not a
// mistake. The caller passes `now` as the lower bound, so a slot that has
// already started is still excluded.
func (q *Queries) ListFreeSlotsBetween(ctx context.Context, arg ListFreeSlotsBetweenParams) ([]ScheduleSlot, error) {
	rows, err := q.db.QueryContext(ctx, listFreeSlotsBetween, arg.FromStartsAt, arg.ToStartsAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleSlot{}
	for rows.Next() {
		var i ScheduleSlot
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SlotDate,
			&i.StartTime,
			&i.EndTime,
			&i.StartsAt,
			&i.EndsAt,
			&i.Capacity,
			&i.BookedCount,
			&i.IsActive,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByDateRange = `-- name: ListSlotsByDateRange :many
SELECT id, service_id, slot_date, start_time, end_time, starts_at, ends_at, capacity, booked_count, is_active, note, created_at, updated_at FROM schedule_slots
WHERE slot_date BETWEEN ? AND ?
ORDER BY slot_date ASC, start_time ASC
`

type ListSlotsByDateRangeParams struct {
	FromSlotDate time.Time `json:"from_slot_date"`
	ToSlotDate   time.Time `json:"to_slot_date"`
}

// The admin calendar / list view.
func (q *Queries) ListSlotsByDateRange(ctx context.Context, arg ListSlotsByDateRangeParams) ([]ScheduleSlot, error) {
	rows, err := q.db.QueryContext(ctx, listSlotsByDateRange, arg.FromSlotDate, arg.ToSlotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleSlot{}
	for rows.Next() {
		var i ScheduleSlot
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SlotDate,
			&i.StartTime,
			&i.EndTime,
			&i.StartsAt,
			&i.EndsAt,
			&i.Capacity,
			&i.BookedCount,
			&i.IsActive,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recountSlotBooked = `-- name: RecountSlotBooked :exec
UPDATE schedule_slots s
SET s.booked_count = (
  SELECT COUNT(*) FROM bookings b
  WHERE b.slot_id = s.id AND b.status NOT IN ('cancelled', 'expired')
)
WHERE s.id = ?
`

// Repair tool for the admin panel and tests. Not part of any normal write path;
// if this ever changes a row in production, something upstream is broken.
func (q *Queries) RecountSlotBooked(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, recountSlotBooked, id)
	return err
}

const releaseSlot = `-- name: ReleaseSlot :exec
UPDATE schedule_slots SET booked_count = GREATEST(booked_count - 1, 0) WHERE id = ?
`

// The guarded decrement. The CALLER must have observed a real status transition
// first — RowsAffected() == 1 from ExpireBooking or CancelBooking — inside the
// same transaction. Never call this unconditionally: the expiry ticker and the
// Midtrans webhook can both reach the same booking, and only the one that
// actually moved the status may release the slot.
//
// GREATEST(..., 0) means even a logic error cannot drive the counter negative.
func (q *Queries) ReleaseSlot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, releaseSlot, id)
	return err
}

const setSlotActive = `-- name: SetSlotActive :exec
UPDATE schedule_slots SET is_active = ? WHERE id = ?
`

type SetSlotActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetSlotActive(ctx context.Context, arg SetSlotActiveParams) error {
	_, err := q.db.ExecContext(ctx, setSlotActive, arg.IsActive, arg.ID)
	return err
}

const setSlotActiveInRange = `-- name: SetSlotActiveInRange :execresult
UPDATE schedule_slots SET is_active = ? WHERE slot_date BETWEEN ? AND ?
`

type SetSlotActiveInRangeParams struct {
	IsActive     bool      `json:"is_active"`
	FromSlotDate time.Time `json:"from_slot_date"`
	ToSlotDate   time.Time `json:"to_slot_date"`
}

func (q *Queries) SetSlotActiveInRange(ctx context.Context, arg SetSlotActiveInRangeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setSlotActiveInRange, arg.IsActive, arg.FromSlotDate, arg.ToSlotDate)
}

const updateSlot = `-- name: UpdateSlot :exec
UPDATE schedule_slots SET
  slot_date  = ?,
  start_time = ?,
  end_time   = ?,
  capacity   = ?,
  is_active  = ?,
  note       = ?
WHERE id = ?
`

type UpdateSlotParams struct {
	SlotDate  time.Time      `json:"slot_date"`
	StartTime string         `json:"start_time"`
	EndTime   string         `json:"end_time"`
	Capacity  int32          `json:"capacity"`
	IsActive  bool           `json:"is_active"`
	Note      sql.NullString `json:"note"`
	ID        int64          `json:"id"`
}

// Lowering capacity below booked_count violates chk_slots_count and surfaces as
// a constraint error, which the handler renders as "kapasitas tidak boleh lebih
// kecil dari jumlah booking".
//
// is_active is written here as well as by SetSlotActive: the edit form owns the
// flag alongside every other field, and leaving it out would make saving the
// form silently discard a status change the admin just made.
func (q *Queries) UpdateSlot(ctx context.Context, arg UpdateSlotParams) error {
	_, err := q.db.ExecContext(ctx, updateSlot,
		arg.SlotDate,
		arg.StartTime,
		arg.EndTime,
		arg.Capacity,
		arg.IsActive,
		arg.Note,
		arg.ID,
	)
	return err
}
