// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countBookingsForService = `-- name: CountBookingsForService :one
SELECT COUNT(*) AS total FROM bookings WHERE service_id = ?
`

// The admin panel calls this before offering delete.
func (q *Queries) CountBookingsForService(ctx context.Context, serviceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookingsForService, serviceID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countServicesAdmin = `-- name: CountServicesAdmin :one
SELECT COUNT(*) AS total FROM services WHERE name LIKE ?
`

func (q *Queries) CountServicesAdmin(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServicesAdmin, search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createService = `-- name: CreateService :execresult
INSERT INTO services (slug, name, description, price, duration_minutes, image_path,
                      is_active, is_coming_soon, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateServiceParams struct {
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Price           string         `json:"price"`
	DurationMinutes int32          `json:"duration_minutes"`
	ImagePath       sql.NullString `json:"image_path"`
	IsActive        bool           `json:"is_active"`
	IsComingSoon    bool           `json:"is_coming_soon"`
	SortOrder       int32          `json:"sort_order"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createService,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.DurationMinutes,
		arg.ImagePath,
		arg.IsActive,
		arg.IsComingSoon,
		arg.SortOrder,
	)
}

const deleteService = `-- name: DeleteService :execresult
DELETE FROM services WHERE id = ?
`

// Blocked by fk_bookings_service (RESTRICT) once any booking references it. The
// handler checks CountBookingsForService first and offers deactivation instead.
func (q *Queries) DeleteService(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteService, id)
}

const getActiveServiceBySlug = `-- name: GetActiveServiceBySlug :one
SELECT id, slug, name, description, price, duration_minutes, image_path, is_active, is_coming_soon, sort_order, created_at, updated_at FROM services WHERE slug = ? AND is_active = 1 LIMIT 1
`

// The public detail page. Inactive services must 404, not render.
func (q *Queries) GetActiveServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getActiveServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.ImagePath,
		&i.IsActive,
		&i.IsComingSoon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one

SELECT id, slug, name, description, price, duration_minutes, image_path, is_active, is_coming_soon, sort_order, created_at, updated_at FROM services WHERE id = ? LIMIT 1
`

// services — the layanan catalogue.
func (q *Queries) GetService(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.ImagePath,
		&i.IsActive,
		&i.IsComingSoon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceBySlug = `-- name: GetServiceBySlug :one
SELECT id, slug, name, description, price, duration_minutes, image_path, is_active, is_coming_soon, sort_order, created_at, updated_at FROM services WHERE slug = ? LIMIT 1
`

func (q *Queries) GetServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.ImagePath,
		&i.IsActive,
		&i.IsComingSoon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT id, slug, name, description, price, duration_minutes, image_path, is_active, is_coming_soon, sort_order, created_at, updated_at FROM services WHERE is_active = 1 ORDER BY sort_order ASC, id ASC
`

// Public listing. Includes coming-soon services: they are shown with a label.
func (q *Queries) ListActiveServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listActiveServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.DurationMinutes,
			&i.ImagePath,
			&i.IsActive,
			&i.IsComingSoon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookableServices = `-- name: ListBookableServices :many
SELECT id, slug, name, description, price, duration_minutes, image_path, is_active, is_coming_soon, sort_order, created_at, updated_at FROM services
WHERE is_active = 1 AND is_coming_soon = 0
ORDER BY sort_order ASC, id ASC
`

// Booking step 1. Coming-soon services appear on the public site but cannot be
// booked, so they are excluded here.
func (q *Queries) ListBookableServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listBookableServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.DurationMinutes,
			&i.ImagePath,
			&i.IsActive,
			&i.IsComingSoon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesAdmin = `-- name: ListServicesAdmin :many
SELECT id, slug, name, description, price, duration_minutes, image_path, is_active, is_coming_soon, sort_order, created_at, updated_at FROM services
WHERE name LIKE ?
ORDER BY sort_order ASC, id ASC
LIMIT ? OFFSET ?
`

type ListServicesAdminParams struct {
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// Pass "%" for an empty search box.
func (q *Queries) ListServicesAdmin(ctx context.Context, arg ListServicesAdminParams) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesAdmin, arg.Search, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.DurationMinutes,
			&i.ImagePath,
			&i.IsActive,
			&i.IsComingSoon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceSlugTaken = `-- name: ServiceSlugTaken :one
SELECT EXISTS(SELECT 1 FROM services WHERE slug = ? AND id <> ?) AS taken
`

type ServiceSlugTakenParams struct {
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

// Pass 0 as the id when creating, so no row is excluded.
func (q *Queries) ServiceSlugTaken(ctx context.Context, arg ServiceSlugTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, serviceSlugTaken, arg.Slug, arg.ID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const setServiceActive = `-- name: SetServiceActive :exec
UPDATE services SET is_active = ? WHERE id = ?
`

type SetServiceActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetServiceActive(ctx context.Context, arg SetServiceActiveParams) error {
	_, err := q.db.ExecContext(ctx, setServiceActive, arg.IsActive, arg.ID)
	return err
}

const setServiceComingSoon = `-- name: SetServiceComingSoon :exec
UPDATE services SET is_coming_soon = ? WHERE id = ?
`

type SetServiceComingSoonParams struct {
	IsComingSoon bool  `json:"is_coming_soon"`
	ID           int64 `json:"id"`
}

func (q *Queries) SetServiceComingSoon(ctx context.Context, arg SetServiceComingSoonParams) error {
	_, err := q.db.ExecContext(ctx, setServiceComingSoon, arg.IsComingSoon, arg.ID)
	return err
}

const updateService = `-- name: UpdateService :exec
UPDATE services SET
  slug             = ?,
  name             = ?,
  description      = ?,
  price            = ?,
  duration_minutes = ?,
  is_active        = ?,
  is_coming_soon   = ?,
  sort_order       = ?
WHERE id = ?
`

type UpdateServiceParams struct {
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Price           string         `json:"price"`
	DurationMinutes int32          `json:"duration_minutes"`
	IsActive        bool           `json:"is_active"`
	IsComingSoon    bool           `json:"is_coming_soon"`
	SortOrder       int32          `json:"sort_order"`
	ID              int64          `json:"id"`
}

// image_path is updated separately so a form submit without a new file cannot
// blank an existing image.
func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.DurationMinutes,
		arg.IsActive,
		arg.IsComingSoon,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateServiceImage = `-- name: UpdateServiceImage :exec
UPDATE services SET image_path = ? WHERE id = ?
`

type UpdateServiceImageParams struct {
	ImagePath sql.NullString `json:"image_path"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateServiceImage(ctx context.Context, arg UpdateServiceImageParams) error {
	_, err := q.db.ExecContext(ctx, updateServiceImage, arg.ImagePath, arg.ID)
	return err
}
