// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE setting_key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, settingKey string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, settingKey)
	return err
}

const getSetting = `-- name: GetSetting :one

SELECT setting_value FROM settings WHERE setting_key = ? LIMIT 1
`

// settings — key/value site configuration, editable from /admin/pengaturan.
//
// Where a key also exists in the environment (payment_expiry_minutes vs
// PAYMENT_EXPIRY_MINUTES), the DB row wins when present and parseable; the env
// value is the fallback and the fail-fast default. config stays the only reader
// of os.Getenv.
func (q *Queries) GetSetting(ctx context.Context, settingKey string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSetting, settingKey)
	var setting_value sql.NullString
	err := row.Scan(&setting_value)
	return setting_value, err
}

const listSettings = `-- name: ListSettings :many
SELECT setting_key, setting_value, updated_at FROM settings ORDER BY setting_key ASC
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.SettingKey, &i.SettingValue, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (setting_key, setting_value) VALUES (?, ?)
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)
`

type UpsertSettingParams struct {
	SettingKey   string         `json:"setting_key"`
	SettingValue sql.NullString `json:"setting_value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.SettingKey, arg.SettingValue)
	return err
}
