// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: therapists.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addTherapistService = `-- name: AddTherapistService :exec
INSERT INTO therapist_services (therapist_id, service_id) VALUES (?, ?)
`

type AddTherapistServiceParams struct {
	TherapistID int64 `json:"therapist_id"`
	ServiceID   int64 `json:"service_id"`
}

func (q *Queries) AddTherapistService(ctx context.Context, arg AddTherapistServiceParams) error {
	_, err := q.db.ExecContext(ctx, addTherapistService, arg.TherapistID, arg.ServiceID)
	return err
}

const countTherapistsAdmin = `-- name: CountTherapistsAdmin :one
SELECT COUNT(*) AS total FROM therapists WHERE name LIKE ?
`

func (q *Queries) CountTherapistsAdmin(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTherapistsAdmin, search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTherapist = `-- name: CreateTherapist :execresult
INSERT INTO therapists (slug, name, specialization, bio, certifications,
                        years_experience, image_path, is_active, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTherapistParams struct {
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Specialization  sql.NullString `json:"specialization"`
	Bio             sql.NullString `json:"bio"`
	Certifications  sql.NullString `json:"certifications"`
	YearsExperience sql.NullInt32  `json:"years_experience"`
	ImagePath       sql.NullString `json:"image_path"`
	IsActive        bool           `json:"is_active"`
	SortOrder       int32          `json:"sort_order"`
}

func (q *Queries) CreateTherapist(ctx context.Context, arg CreateTherapistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTherapist,
		arg.Slug,
		arg.Name,
		arg.Specialization,
		arg.Bio,
		arg.Certifications,
		arg.YearsExperience,
		arg.ImagePath,
		arg.IsActive,
		arg.SortOrder,
	)
}

const deleteTherapist = `-- name: DeleteTherapist :execresult
DELETE FROM therapists WHERE id = ?
`

// Nothing references a therapist except therapist_services, which CASCADEs, so
// unlike DeleteService this can never be blocked by a foreign key.
func (q *Queries) DeleteTherapist(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTherapist, id)
}

const deleteTherapistServices = `-- name: DeleteTherapistServices :exec
DELETE FROM therapist_services WHERE therapist_id = ?
`

func (q *Queries) DeleteTherapistServices(ctx context.Context, therapistID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTherapistServices, therapistID)
	return err
}

const getActiveTherapistBySlug = `-- name: GetActiveTherapistBySlug :one
SELECT id, slug, name, specialization, bio, certifications, years_experience, image_path, is_active, sort_order, created_at, updated_at FROM therapists WHERE slug = ? AND is_active = 1 LIMIT 1
`

// The public profile page. Inactive therapists must 404, not render.
func (q *Queries) GetActiveTherapistBySlug(ctx context.Context, slug string) (Therapist, error) {
	row := q.db.QueryRowContext(ctx, getActiveTherapistBySlug, slug)
	var i Therapist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Specialization,
		&i.Bio,
		&i.Certifications,
		&i.YearsExperience,
		&i.ImagePath,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTherapist = `-- name: GetTherapist :one

SELECT id, slug, name, specialization, bio, certifications, years_experience, image_path, is_active, sort_order, created_at, updated_at FROM therapists WHERE id = ? LIMIT 1
`

// therapists — the terapis profiles, and which layanan each one handles.
func (q *Queries) GetTherapist(ctx context.Context, id int64) (Therapist, error) {
	row := q.db.QueryRowContext(ctx, getTherapist, id)
	var i Therapist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Specialization,
		&i.Bio,
		&i.Certifications,
		&i.YearsExperience,
		&i.ImagePath,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveTherapists = `-- name: HasActiveTherapists :one
SELECT EXISTS(SELECT 1 FROM therapists WHERE is_active = 1) AS present
`

// Whether the public site advertises the terapis section at all. EXISTS rather
// than a COUNT: the answer is a yes/no, and idx_therapists_active_sort makes it
// an index-only lookup.
func (q *Queries) HasActiveTherapists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveTherapists)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const listActiveTherapists = `-- name: ListActiveTherapists :many
SELECT id, slug, name, specialization, bio, certifications, years_experience, image_path, is_active, sort_order, created_at, updated_at FROM therapists WHERE is_active = 1 ORDER BY sort_order ASC, id ASC
`

// Public listing.
func (q *Queries) ListActiveTherapists(ctx context.Context) ([]Therapist, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTherapists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Therapist{}
	for rows.Next() {
		var i Therapist
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Specialization,
			&i.Bio,
			&i.Certifications,
			&i.YearsExperience,
			&i.ImagePath,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTherapistsForService = `-- name: ListActiveTherapistsForService :many
SELECT t.id, t.slug, t.name, t.specialization, t.bio, t.certifications, t.years_experience, t.image_path, t.is_active, t.sort_order, t.created_at, t.updated_at FROM therapists t
JOIN therapist_services ts ON ts.therapist_id = t.id
WHERE ts.service_id = ? AND t.is_active = 1
ORDER BY t.sort_order ASC, t.id ASC
`

// The reverse link, for the strip on /layanan/{slug}.
func (q *Queries) ListActiveTherapistsForService(ctx context.Context, serviceID int64) ([]Therapist, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTherapistsForService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Therapist{}
	for rows.Next() {
		var i Therapist
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Specialization,
			&i.Bio,
			&i.Certifications,
			&i.YearsExperience,
			&i.ImagePath,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceIDsForTherapist = `-- name: ListServiceIDsForTherapist :many
SELECT service_id FROM therapist_services WHERE therapist_id = ?
`

// Drives the admin form's checkbox state. Deliberately unfiltered: a tag
// pointing at a deactivated layanan must still be visible to the service layer,
// which decides what to do with it.
func (q *Queries) ListServiceIDsForTherapist(ctx context.Context, therapistID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listServiceIDsForTherapist, therapistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var service_id int64
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTagsForActiveTherapists = `-- name: ListServiceTagsForActiveTherapists :many
SELECT ts.therapist_id, s.id, s.slug, s.name
FROM therapist_services ts
JOIN services s   ON s.id = ts.service_id
JOIN therapists t ON t.id = ts.therapist_id
WHERE t.is_active = 1 AND s.is_active = 1
ORDER BY ts.therapist_id ASC, s.sort_order ASC, s.id ASC
`

type ListServiceTagsForActiveTherapistsRow struct {
	TherapistID int64  `json:"therapist_id"`
	ID          int64  `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
}

// One query for the whole /terapis grid, grouped by therapist_id in Go. The
// alternative is a ListServicesForTherapist per card.
func (q *Queries) ListServiceTagsForActiveTherapists(ctx context.Context) ([]ListServiceTagsForActiveTherapistsRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceTagsForActiveTherapists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTagsForActiveTherapistsRow{}
	for rows.Next() {
		var i ListServiceTagsForActiveTherapistsRow
		if err := rows.Scan(
			&i.TherapistID,
			&i.ID,
			&i.Slug,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForTherapist = `-- name: ListServicesForTherapist :many

SELECT s.id, s.slug, s.name, s.description, s.price, s.duration_minutes, s.image_path, s.is_active, s.is_coming_soon, s.sort_order, s.created_at, s.updated_at FROM services s
JOIN therapist_services ts ON ts.service_id = s.id
WHERE ts.therapist_id = ? AND s.is_active = 1
ORDER BY s.sort_order ASC, s.id ASC
`

// ---------------------------------------------------------------------------
// therapist_services
// ---------------------------------------------------------------------------
// The public profile page. Active layanan only, in the catalogue's own order.
func (q *Queries) ListServicesForTherapist(ctx context.Context, therapistID int64) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesForTherapist, therapistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.DurationMinutes,
			&i.ImagePath,
			&i.IsActive,
			&i.IsComingSoon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTherapistsAdmin = `-- name: ListTherapistsAdmin :many
SELECT id, slug, name, specialization, bio, certifications, years_experience, image_path, is_active, sort_order, created_at, updated_at FROM therapists
WHERE name LIKE ?
ORDER BY sort_order ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTherapistsAdminParams struct {
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// Pass "%" for an empty search box.
func (q *Queries) ListTherapistsAdmin(ctx context.Context, arg ListTherapistsAdminParams) ([]Therapist, error) {
	rows, err := q.db.QueryContext(ctx, listTherapistsAdmin, arg.Search, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Therapist{}
	for rows.Next() {
		var i Therapist
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Specialization,
			&i.Bio,
			&i.Certifications,
			&i.YearsExperience,
			&i.ImagePath,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTherapistActive = `-- name: SetTherapistActive :exec
UPDATE therapists SET is_active = ? WHERE id = ?
`

type SetTherapistActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetTherapistActive(ctx context.Context, arg SetTherapistActiveParams) error {
	_, err := q.db.ExecContext(ctx, setTherapistActive, arg.IsActive, arg.ID)
	return err
}

const therapistSlugTaken = `-- name: TherapistSlugTaken :one
SELECT EXISTS(SELECT 1 FROM therapists WHERE slug = ? AND id <> ?) AS taken
`

type TherapistSlugTakenParams struct {
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

// Pass 0 as the id when creating, so no row is excluded.
func (q *Queries) TherapistSlugTaken(ctx context.Context, arg TherapistSlugTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, therapistSlugTaken, arg.Slug, arg.ID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const updateTherapist = `-- name: UpdateTherapist :exec
UPDATE therapists SET
  name             = ?,
  specialization   = ?,
  bio              = ?,
  certifications   = ?,
  years_experience = ?,
  is_active        = ?,
  sort_order       = ?
WHERE id = ?
`

type UpdateTherapistParams struct {
	Name            string         `json:"name"`
	Specialization  sql.NullString `json:"specialization"`
	Bio             sql.NullString `json:"bio"`
	Certifications  sql.NullString `json:"certifications"`
	YearsExperience sql.NullInt32  `json:"years_experience"`
	IsActive        bool           `json:"is_active"`
	SortOrder       int32          `json:"sort_order"`
	ID              int64          `json:"id"`
}

// image_path is updated separately so a form submit without a new file cannot
// blank an existing photo. slug is absent for the same reason it is absent from
// UpdateService: it is the public URL and is allocated once, at creation.
func (q *Queries) UpdateTherapist(ctx context.Context, arg UpdateTherapistParams) error {
	_, err := q.db.ExecContext(ctx, updateTherapist,
		arg.Name,
		arg.Specialization,
		arg.Bio,
		arg.Certifications,
		arg.YearsExperience,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateTherapistImage = `-- name: UpdateTherapistImage :exec
UPDATE therapists SET image_path = ? WHERE id = ?
`

type UpdateTherapistImageParams struct {
	ImagePath sql.NullString `json:"image_path"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateTherapistImage(ctx context.Context, arg UpdateTherapistImageParams) error {
	_, err := q.db.ExecContext(ctx, updateTherapistImage, arg.ImagePath, arg.ID)
	return err
}
