// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) AS total FROM users WHERE role = 'admin' AND is_active = 1
`

// The last-admin guard: demoting or deactivating the only remaining admin locks
// everyone out of the panel, and TPJ owns no credentials to get back in with.
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countBookingsForUser = `-- name: CountBookingsForUser :one
SELECT COUNT(*) AS total FROM bookings WHERE user_id = ?
`

// Shown on the user list, so an operator can see whether a row is a real
// customer before deactivating it.
func (q *Queries) CountBookingsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookingsForUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS total FROM users WHERE name LIKE ? OR email LIKE ?
`

type CountUsersParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Search, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUser = `-- name: GetUser :one

SELECT id, appskep_user_id, email, name, phone, address, latitude, longitude, avatar_path, role, is_active, last_login_at, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

// users — the local mirror of the Appskep identity.
//
// Nothing here authenticates anyone. Identity comes from the Appskep JWT; these
// queries only keep the local mirror in step with it.
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppskepUserID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.AvatarPath,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAppskepID = `-- name: GetUserByAppskepID :one
SELECT id, appskep_user_id, email, name, phone, address, latitude, longitude, avatar_path, role, is_active, last_login_at, created_at, updated_at FROM users WHERE appskep_user_id = ? LIMIT 1
`

func (q *Queries) GetUserByAppskepID(ctx context.Context, appskepUserID uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAppskepID, appskepUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppskepUserID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.AvatarPath,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, appskep_user_id, email, name, phone, address, latitude, longitude, avatar_path, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE name LIKE ? OR email LIKE ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// Pass "%" for an empty search box: name and email are NOT NULL, so LIKE '%'
// matches every row and no SQL branching is needed.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AppskepUserID,
			&i.Email,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.AvatarPath,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = ? WHERE id = ?
`

type SetUserActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUserActive, arg.IsActive, arg.ID)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = ? WHERE id = ?
`

type SetUserRoleParams struct {
	Role UsersRole `json:"role"`
	ID   int64     `json:"id"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, setUserRole, arg.Role, arg.ID)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_path = ? WHERE id = ?
`

type UpdateUserAvatarParams struct {
	AvatarPath sql.NullString `json:"avatar_path"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.AvatarPath, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET phone = ?, address = ?, latitude = ?, longitude = ? WHERE id = ?
`

type UpdateUserProfileParams struct {
	Phone     sql.NullString `json:"phone"`
	Address   sql.NullString `json:"address"`
	Latitude  sql.NullString `json:"latitude"`
	Longitude sql.NullString `json:"longitude"`
	ID        int64          `json:"id"`
}

// Only the locally-owned fields. name and email belong to Appskep and are
// refreshed from the JWT on each login.
//
// latitude and longitude move as a pair, always both, so clearing the map pin
// cannot leave half of one behind.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Phone,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
	)
	return err
}

const upsertUserFromSSO = `-- name: UpsertUserFromSSO :execresult
INSERT INTO users (appskep_user_id, email, name, is_active, last_login_at)
VALUES (?, ?, ?, 1, NOW())
ON DUPLICATE KEY UPDATE
  email         = VALUES(email),
  name          = VALUES(name),
  last_login_at = NOW()
`

type UpsertUserFromSSOParams struct {
	AppskepUserID uint64 `json:"appskep_user_id"`
	Email         string `json:"email"`
	Name          string `json:"name"`
}

// Called on every login. Refreshes the Appskep-owned fields and stamps the
// login. It deliberately does NOT touch `role`: an admin demoted in the Phase 10
// user panel must stay demoted through their next login. Bootstrap promotion
// from ADMIN_USER_IDS is a separate SetUserRole call.
func (q *Queries) UpsertUserFromSSO(ctx context.Context, arg UpsertUserFromSSOParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertUserFromSSO, arg.AppskepUserID, arg.Email, arg.Name)
}
