#!/usr/bin/env bash
# Build static/img/icons.svg — one <symbol> per icon, referenced from templates
# by the `icon` template helper as <use href="/static/img/icons.svg#name">.
#
# The sprite is committed. This script only runs when the icon list below
# changes, so a clean checkout needs no network and the app has no CDN
# dependency (PLAN.md Phase 2). Both sources are permissively licensed:
# Lucide is ISC, Simple Icons is CC0.
set -euo pipefail

cd "$(dirname "$0")/.."

LUCIDE_VERSION=1.27.0
SIMPLE_VERSION=16.27.1
OUT=static/img/icons.svg

# Lucide icons, on a 24x24 grid with stroke styling inherited from the <use>.
LUCIDE=(
  alert-circle alert-triangle arrow-left arrow-right ban calendar
  calendar-days check check-circle chevron-down chevron-left chevron-right
  circle-help clock copy credit-card download external-link eye filter
  image info layout-dashboard loader-circle log-out mail map-pin menu
  pencil phone plus receipt refresh-cw search settings sparkles
  trash-2 user users wallet x
)

# Simple Icons brand marks, on a 24x24 grid, solid fill.
SIMPLE=(whatsapp instagram)

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# strip_svg pulls the inner markup out of a downloaded <svg> element. Newlines
# are collapsed first: both sources wrap the opening <svg> tag across several
# lines, so a line-based match would never see it whole and would leave a nested
# <svg> inside the <symbol> — which renders as nothing.
strip_svg() {
  tr '\n' ' ' <"$1" \
    | sed -e 's/<?xml[^>]*?>//g' \
          -e 's/<!--[^>]*-->//g' \
          -e 's#<svg[^>]*>##' \
          -e 's#</svg>##' \
          -e 's#<title>[^<]*</title>##' \
    | sed -e 's/  */ /g' -e 's/^ //' -e 's/ $//'
}

{
  echo '<?xml version="1.0" encoding="UTF-8"?>'
  echo '<!-- GENERATED by scripts/build-icons.sh — do not edit by hand. -->'
  echo "<!-- lucide ${LUCIDE_VERSION} (ISC) · simple-icons ${SIMPLE_VERSION} (CC0) -->"
  echo '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">'

  for name in "${LUCIDE[@]}"; do
    url="https://unpkg.com/lucide-static@${LUCIDE_VERSION}/icons/${name}.svg"
    if ! curl -fsSL -o "$tmp/$name.svg" "$url"; then
      echo "FAILED: lucide/$name ($url)" >&2
      exit 1
    fi
    # Lucide's own attributes (fill/stroke/stroke-width/linecap/linejoin) live on
    # the <svg> root, which <use> does not inherit — restate them on the symbol.
    printf '  <symbol id="%s" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">%s</symbol>\n' \
      "$name" "$(strip_svg "$tmp/$name.svg")"
  done

  for name in "${SIMPLE[@]}"; do
    url="https://unpkg.com/simple-icons@${SIMPLE_VERSION}/icons/${name}.svg"
    if ! curl -fsSL -o "$tmp/brand-$name.svg" "$url"; then
      echo "FAILED: simple-icons/$name ($url)" >&2
      exit 1
    fi
    # Brand marks are solid shapes, so they fill rather than stroke.
    printf '  <symbol id="brand-%s" viewBox="0 0 24 24" fill="currentColor" stroke="none">%s</symbol>\n' \
      "$name" "$(strip_svg "$tmp/brand-$name.svg")"
  done

  echo '</svg>'
} >"$OUT.tmp"

mv "$OUT.tmp" "$OUT"
printf 'wrote %s (%d icons, %s)\n' "$OUT" $(( ${#LUCIDE[@]} + ${#SIMPLE[@]} )) \
  "$(du -h "$OUT" | cut -f1 | tr -d ' ')"
